/*
 * This file is part of the Krypton project, licensed under the Apache License v2.0
 *
 * Copyright (C) 2021-2023 KryptonMC and the contributors of the Krypton project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kryptonmc.generators

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.STRING
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import net.minecraft.tags.TagKey
import java.nio.file.Path
import kotlin.io.path.exists
import kotlin.io.path.writeText

class TagGenerator(private val output: Path) {

    fun <S> run(catalogueType: Class<S>, name: String, typeName: String, parameterType: TypeName, parameterTypeName: String) {
        val returnType = TAG.parameterizedBy(parameterType)
        val file = FileSpec.builder(TAGS_PACKAGE, name)
            .indent("    ")
            .addImport("net.kyori.adventure.key", "Key")
            .addImport("$PACKAGE.resource", "ResourceKeys")
        val outputClass = TypeSpec.objectBuilder(ClassName(TAGS_PACKAGE, name)).autoGenerated().privateStaticFunction("get", returnType) {
            addParameter("key", STRING)
            addCode("return·TagKey.of(ResourceKeys.$typeName,·Key.key(key))")
        }
        catalogueType.collectFields(TagKey::class.java).forEach { outputClass.field(it.name, returnType, "get(\"${it.value.location.path}\")") }
        val out = StringBuilder()
        file.addType(outputClass.build()).build().writeTo(out)
        val outputFile = output.resolve("org/kryptonmc/api/tags").tryCreateDirectories().resolve("$name.kt")
        if (outputFile.exists()) return
        outputFile.tryCreateFile().writeText(out.toString().performReplacements("TagKey<$parameterTypeName>", name))
    }

    inline fun <reified S> run(name: String, typeName: String, parameterType: TypeName, parameterTypeName: String) {
        run(S::class.java, name, typeName, parameterType, parameterTypeName)
    }

    companion object {

        private const val TAGS_PACKAGE = "$PACKAGE.tags"
        private val TAG = ClassName(TAGS_PACKAGE, "TagKey")
    }
}
