/*
 * This file is part of the Krypton API, licensed under the MIT license.
 *
 * Copyright (C) 2021-2022 KryptonMC and the contributors to the Krypton project.
 *
 * This project is licensed under the terms of the MIT license.
 * For more details, please reference the LICENSE file in the api top-level directory.
 */
package org.kryptonmc.api.map.color

import java.awt.Color

/**
 * A colour that can be put on a map.
 *
 * @param type the type of the colour
 * @param brightness the brightness of the colour
 */
public enum class MapColor(
    @get:JvmName("type") public val type: MapColorType,
    @get:JvmName("brightness") public val brightness: MapColorBrightness
) {

    NONE_LOW(MapColorType.NONE, MapColorBrightness.LOW),
    NONE_NORMAL(MapColorType.NONE, MapColorBrightness.NORMAL),
    NONE_HIGH(MapColorType.NONE, MapColorBrightness.HIGH),
    NONE_LOWEST(MapColorType.NONE, MapColorBrightness.LOWEST),
    GRASS_LOW(MapColorType.GRASS, MapColorBrightness.LOW),
    GRASS_NORMAL(MapColorType.GRASS, MapColorBrightness.NORMAL),
    GRASS_HIGH(MapColorType.GRASS, MapColorBrightness.HIGH),
    GRASS_LOWEST(MapColorType.GRASS, MapColorBrightness.LOWEST),
    SAND_LOW(MapColorType.SAND, MapColorBrightness.LOW),
    SAND_NORMAL(MapColorType.SAND, MapColorBrightness.NORMAL),
    SAND_HIGH(MapColorType.SAND, MapColorBrightness.HIGH),
    SAND_LOWEST(MapColorType.SAND, MapColorBrightness.LOWEST),
    WOOL_LOW(MapColorType.WOOL, MapColorBrightness.LOW),
    WOOL_NORMAL(MapColorType.WOOL, MapColorBrightness.NORMAL),
    WOOL_HIGH(MapColorType.WOOL, MapColorBrightness.HIGH),
    WOOL_LOWEST(MapColorType.WOOL, MapColorBrightness.LOWEST),
    FIRE_LOW(MapColorType.FIRE, MapColorBrightness.LOW),
    FIRE_NORMAL(MapColorType.FIRE, MapColorBrightness.NORMAL),
    FIRE_HIGH(MapColorType.FIRE, MapColorBrightness.HIGH),
    FIRE_LOWEST(MapColorType.FIRE, MapColorBrightness.LOWEST),
    ICE_LOW(MapColorType.ICE, MapColorBrightness.LOW),
    ICE_NORMAL(MapColorType.ICE, MapColorBrightness.NORMAL),
    ICE_HIGH(MapColorType.ICE, MapColorBrightness.HIGH),
    ICE_LOWEST(MapColorType.ICE, MapColorBrightness.LOWEST),
    METAL_LOW(MapColorType.METAL, MapColorBrightness.LOW),
    METAL_NORMAL(MapColorType.METAL, MapColorBrightness.NORMAL),
    METAL_HIGH(MapColorType.METAL, MapColorBrightness.HIGH),
    METAL_LOWEST(MapColorType.METAL, MapColorBrightness.LOWEST),
    PLANT_LOW(MapColorType.PLANT, MapColorBrightness.LOW),
    PLANT_NORMAL(MapColorType.PLANT, MapColorBrightness.NORMAL),
    PLANT_HIGH(MapColorType.PLANT, MapColorBrightness.HIGH),
    PLANT_LOWEST(MapColorType.PLANT, MapColorBrightness.LOWEST),
    SNOW_LOW(MapColorType.SNOW, MapColorBrightness.LOW),
    SNOW_NORMAL(MapColorType.SNOW, MapColorBrightness.NORMAL),
    SNOW_HIGH(MapColorType.SNOW, MapColorBrightness.HIGH),
    SNOW_LOWEST(MapColorType.SNOW, MapColorBrightness.LOWEST),
    CLAY_LOW(MapColorType.CLAY, MapColorBrightness.LOW),
    CLAY_NORMAL(MapColorType.CLAY, MapColorBrightness.NORMAL),
    CLAY_HIGH(MapColorType.CLAY, MapColorBrightness.HIGH),
    CLAY_LOWEST(MapColorType.CLAY, MapColorBrightness.LOWEST),
    DIRT_LOW(MapColorType.DIRT, MapColorBrightness.LOW),
    DIRT_NORMAL(MapColorType.DIRT, MapColorBrightness.NORMAL),
    DIRT_HIGH(MapColorType.DIRT, MapColorBrightness.HIGH),
    DIRT_LOWEST(MapColorType.DIRT, MapColorBrightness.LOWEST),
    STONE_LOW(MapColorType.STONE, MapColorBrightness.LOW),
    STONE_NORMAL(MapColorType.STONE, MapColorBrightness.NORMAL),
    STONE_HIGH(MapColorType.STONE, MapColorBrightness.HIGH),
    STONE_LOWEST(MapColorType.STONE, MapColorBrightness.LOWEST),
    WATER_LOW(MapColorType.WATER, MapColorBrightness.LOW),
    WATER_NORMAL(MapColorType.WATER, MapColorBrightness.NORMAL),
    WATER_HIGH(MapColorType.WATER, MapColorBrightness.HIGH),
    WATER_LOWEST(MapColorType.WATER, MapColorBrightness.LOWEST),
    WOOD_LOW(MapColorType.WOOD, MapColorBrightness.LOW),
    WOOD_NORMAL(MapColorType.WOOD, MapColorBrightness.NORMAL),
    WOOD_HIGH(MapColorType.WOOD, MapColorBrightness.HIGH),
    WOOD_LOWEST(MapColorType.WOOD, MapColorBrightness.LOWEST),
    QUARTZ_LOW(MapColorType.QUARTZ, MapColorBrightness.LOW),
    QUARTZ_NORMAL(MapColorType.QUARTZ, MapColorBrightness.NORMAL),
    QUARTZ_HIGH(MapColorType.QUARTZ, MapColorBrightness.HIGH),
    QUARTZ_LOWEST(MapColorType.QUARTZ, MapColorBrightness.LOWEST),
    COLOR_ORANGE_LOW(MapColorType.COLOR_ORANGE, MapColorBrightness.LOW),
    COLOR_ORANGE_NORMAL(MapColorType.COLOR_ORANGE, MapColorBrightness.NORMAL),
    COLOR_ORANGE_HIGH(MapColorType.COLOR_ORANGE, MapColorBrightness.HIGH),
    COLOR_ORANGE_LOWEST(MapColorType.COLOR_ORANGE, MapColorBrightness.LOWEST),
    COLOR_MAGENTA_LOW(MapColorType.COLOR_MAGENTA, MapColorBrightness.LOW),
    COLOR_MAGENTA_NORMAL(MapColorType.COLOR_MAGENTA, MapColorBrightness.NORMAL),
    COLOR_MAGENTA_HIGH(MapColorType.COLOR_MAGENTA, MapColorBrightness.HIGH),
    COLOR_MAGENTA_LOWEST(MapColorType.COLOR_MAGENTA, MapColorBrightness.LOWEST),
    COLOR_LIGHT_BLUE_LOW(MapColorType.COLOR_LIGHT_BLUE, MapColorBrightness.LOW),
    COLOR_LIGHT_BLUE_NORMAL(MapColorType.COLOR_LIGHT_BLUE, MapColorBrightness.NORMAL),
    COLOR_LIGHT_BLUE_HIGH(MapColorType.COLOR_LIGHT_BLUE, MapColorBrightness.HIGH),
    COLOR_LIGHT_BLUE_LOWEST(MapColorType.COLOR_LIGHT_BLUE, MapColorBrightness.LOWEST),
    COLOR_YELLOW_LOW(MapColorType.COLOR_YELLOW, MapColorBrightness.LOW),
    COLOR_YELLOW_NORMAL(MapColorType.COLOR_YELLOW, MapColorBrightness.NORMAL),
    COLOR_YELLOW_HIGH(MapColorType.COLOR_YELLOW, MapColorBrightness.HIGH),
    COLOR_YELLOW_LOWEST(MapColorType.COLOR_YELLOW, MapColorBrightness.LOWEST),
    COLOR_LIGHT_GREEN_LOW(MapColorType.COLOR_LIGHT_GREEN, MapColorBrightness.LOW),
    COLOR_LIGHT_GREEN_NORMAL(MapColorType.COLOR_LIGHT_GREEN, MapColorBrightness.NORMAL),
    COLOR_LIGHT_GREEN_HIGH(MapColorType.COLOR_LIGHT_GREEN, MapColorBrightness.HIGH),
    COLOR_LIGHT_GREEN_LOWEST(MapColorType.COLOR_LIGHT_GREEN, MapColorBrightness.LOWEST),
    COLOR_PINK_LOW(MapColorType.COLOR_PINK, MapColorBrightness.LOW),
    COLOR_PINK_NORMAL(MapColorType.COLOR_PINK, MapColorBrightness.NORMAL),
    COLOR_PINK_HIGH(MapColorType.COLOR_PINK, MapColorBrightness.HIGH),
    COLOR_PINK_LOWEST(MapColorType.COLOR_PINK, MapColorBrightness.LOWEST),
    COLOR_GRAY_LOW(MapColorType.COLOR_GRAY, MapColorBrightness.LOW),
    COLOR_GRAY_NORMAL(MapColorType.COLOR_GRAY, MapColorBrightness.NORMAL),
    COLOR_GRAY_HIGH(MapColorType.COLOR_GRAY, MapColorBrightness.HIGH),
    COLOR_GRAY_LOWEST(MapColorType.COLOR_GRAY, MapColorBrightness.LOWEST),
    COLOR_LIGHT_GRAY_LOW(MapColorType.COLOR_LIGHT_GRAY, MapColorBrightness.LOW),
    COLOR_LIGHT_GRAY_NORMAL(MapColorType.COLOR_LIGHT_GRAY, MapColorBrightness.NORMAL),
    COLOR_LIGHT_GRAY_HIGH(MapColorType.COLOR_LIGHT_GRAY, MapColorBrightness.HIGH),
    COLOR_LIGHT_GRAY_LOWEST(MapColorType.COLOR_LIGHT_GRAY, MapColorBrightness.LOWEST),
    COLOR_CYAN_LOW(MapColorType.COLOR_CYAN, MapColorBrightness.LOW),
    COLOR_CYAN_NORMAL(MapColorType.COLOR_CYAN, MapColorBrightness.NORMAL),
    COLOR_CYAN_HIGH(MapColorType.COLOR_CYAN, MapColorBrightness.HIGH),
    COLOR_CYAN_LOWEST(MapColorType.COLOR_CYAN, MapColorBrightness.LOWEST),
    COLOR_PURPLE_LOW(MapColorType.COLOR_PURPLE, MapColorBrightness.LOW),
    COLOR_PURPLE_NORMAL(MapColorType.COLOR_PURPLE, MapColorBrightness.NORMAL),
    COLOR_PURPLE_HIGH(MapColorType.COLOR_PURPLE, MapColorBrightness.HIGH),
    COLOR_PURPLE_LOWEST(MapColorType.COLOR_PURPLE, MapColorBrightness.LOWEST),
    COLOR_BLUE_LOW(MapColorType.COLOR_BLUE, MapColorBrightness.LOW),
    COLOR_BLUE_NORMAL(MapColorType.COLOR_BLUE, MapColorBrightness.NORMAL),
    COLOR_BLUE_HIGH(MapColorType.COLOR_BLUE, MapColorBrightness.HIGH),
    COLOR_BLUE_LOWEST(MapColorType.COLOR_BLUE, MapColorBrightness.LOWEST),
    COLOR_BROWN_LOW(MapColorType.COLOR_BROWN, MapColorBrightness.LOW),
    COLOR_BROWN_NORMAL(MapColorType.COLOR_BROWN, MapColorBrightness.NORMAL),
    COLOR_BROWN_HIGH(MapColorType.COLOR_BROWN, MapColorBrightness.HIGH),
    COLOR_BROWN_LOWEST(MapColorType.COLOR_BROWN, MapColorBrightness.LOWEST),
    COLOR_GREEN_LOW(MapColorType.COLOR_GREEN, MapColorBrightness.LOW),
    COLOR_GREEN_NORMAL(MapColorType.COLOR_GREEN, MapColorBrightness.NORMAL),
    COLOR_GREEN_HIGH(MapColorType.COLOR_GREEN, MapColorBrightness.HIGH),
    COLOR_GREEN_LOWEST(MapColorType.COLOR_GREEN, MapColorBrightness.LOWEST),
    COLOR_RED_LOW(MapColorType.COLOR_RED, MapColorBrightness.LOW),
    COLOR_RED_NORMAL(MapColorType.COLOR_RED, MapColorBrightness.NORMAL),
    COLOR_RED_HIGH(MapColorType.COLOR_RED, MapColorBrightness.HIGH),
    COLOR_RED_LOWEST(MapColorType.COLOR_RED, MapColorBrightness.LOWEST),
    COLOR_BLACK_LOW(MapColorType.COLOR_BLACK, MapColorBrightness.LOW),
    COLOR_BLACK_NORMAL(MapColorType.COLOR_BLACK, MapColorBrightness.NORMAL),
    COLOR_BLACK_HIGH(MapColorType.COLOR_BLACK, MapColorBrightness.HIGH),
    COLOR_BLACK_LOWEST(MapColorType.COLOR_BLACK, MapColorBrightness.LOWEST),
    GOLD_LOW(MapColorType.GOLD, MapColorBrightness.LOW),
    GOLD_NORMAL(MapColorType.GOLD, MapColorBrightness.NORMAL),
    GOLD_HIGH(MapColorType.GOLD, MapColorBrightness.HIGH),
    GOLD_LOWEST(MapColorType.GOLD, MapColorBrightness.LOWEST),
    DIAMOND_LOW(MapColorType.DIAMOND, MapColorBrightness.LOW),
    DIAMOND_NORMAL(MapColorType.DIAMOND, MapColorBrightness.NORMAL),
    DIAMOND_HIGH(MapColorType.DIAMOND, MapColorBrightness.HIGH),
    DIAMOND_LOWEST(MapColorType.DIAMOND, MapColorBrightness.LOWEST),
    LAPIS_LOW(MapColorType.LAPIS, MapColorBrightness.LOW),
    LAPIS_NORMAL(MapColorType.LAPIS, MapColorBrightness.NORMAL),
    LAPIS_HIGH(MapColorType.LAPIS, MapColorBrightness.HIGH),
    LAPIS_LOWEST(MapColorType.LAPIS, MapColorBrightness.LOWEST),
    EMERALD_LOW(MapColorType.EMERALD, MapColorBrightness.LOW),
    EMERALD_NORMAL(MapColorType.EMERALD, MapColorBrightness.NORMAL),
    EMERALD_HIGH(MapColorType.EMERALD, MapColorBrightness.HIGH),
    EMERALD_LOWEST(MapColorType.EMERALD, MapColorBrightness.LOWEST),
    PODZOL_LOW(MapColorType.PODZOL, MapColorBrightness.LOW),
    PODZOL_NORMAL(MapColorType.PODZOL, MapColorBrightness.NORMAL),
    PODZOL_HIGH(MapColorType.PODZOL, MapColorBrightness.HIGH),
    PODZOL_LOWEST(MapColorType.PODZOL, MapColorBrightness.LOWEST),
    NETHER_LOW(MapColorType.NETHER, MapColorBrightness.LOW),
    NETHER_NORMAL(MapColorType.NETHER, MapColorBrightness.NORMAL),
    NETHER_HIGH(MapColorType.NETHER, MapColorBrightness.HIGH),
    NETHER_LOWEST(MapColorType.NETHER, MapColorBrightness.LOWEST),
    TERRACOTTA_WHITE_LOW(MapColorType.TERRACOTTA_WHITE, MapColorBrightness.LOW),
    TERRACOTTA_WHITE_NORMAL(MapColorType.TERRACOTTA_WHITE, MapColorBrightness.NORMAL),
    TERRACOTTA_WHITE_HIGH(MapColorType.TERRACOTTA_WHITE, MapColorBrightness.HIGH),
    TERRACOTTA_WHITE_LOWEST(MapColorType.TERRACOTTA_WHITE, MapColorBrightness.LOWEST),
    TERRACOTTA_ORANGE_LOW(MapColorType.TERRACOTTA_ORANGE, MapColorBrightness.LOW),
    TERRACOTTA_ORANGE_NORMAL(MapColorType.TERRACOTTA_ORANGE, MapColorBrightness.NORMAL),
    TERRACOTTA_ORANGE_HIGH(MapColorType.TERRACOTTA_ORANGE, MapColorBrightness.HIGH),
    TERRACOTTA_ORANGE_LOWEST(MapColorType.TERRACOTTA_ORANGE, MapColorBrightness.LOWEST),
    TERRACOTTA_MAGENTA_LOW(MapColorType.TERRACOTTA_MAGENTA, MapColorBrightness.LOW),
    TERRACOTTA_MAGENTA_NORMAL(MapColorType.TERRACOTTA_MAGENTA, MapColorBrightness.NORMAL),
    TERRACOTTA_MAGENTA_HIGH(MapColorType.TERRACOTTA_MAGENTA, MapColorBrightness.HIGH),
    TERRACOTTA_MAGENTA_LOWEST(MapColorType.TERRACOTTA_MAGENTA, MapColorBrightness.LOWEST),
    TERRACOTTA_LIGHT_BLUE_LOW(MapColorType.TERRACOTTA_LIGHT_BLUE, MapColorBrightness.LOW),
    TERRACOTTA_LIGHT_BLUE_NORMAL(MapColorType.TERRACOTTA_LIGHT_BLUE, MapColorBrightness.NORMAL),
    TERRACOTTA_LIGHT_BLUE_HIGH(MapColorType.TERRACOTTA_LIGHT_BLUE, MapColorBrightness.HIGH),
    TERRACOTTA_LIGHT_BLUE_LOWEST(MapColorType.TERRACOTTA_LIGHT_BLUE, MapColorBrightness.LOWEST),
    TERRACOTTA_YELLOW_LOW(MapColorType.TERRACOTTA_YELLOW, MapColorBrightness.LOW),
    TERRACOTTA_YELLOW_NORMAL(MapColorType.TERRACOTTA_YELLOW, MapColorBrightness.NORMAL),
    TERRACOTTA_YELLOW_HIGH(MapColorType.TERRACOTTA_YELLOW, MapColorBrightness.HIGH),
    TERRACOTTA_YELLOW_LOWEST(MapColorType.TERRACOTTA_YELLOW, MapColorBrightness.LOWEST),
    TERRACOTTA_LIGHT_GREEN_LOW(MapColorType.TERRACOTTA_LIGHT_GREEN, MapColorBrightness.LOW),
    TERRACOTTA_LIGHT_GREEN_NORMAL(MapColorType.TERRACOTTA_LIGHT_GREEN, MapColorBrightness.NORMAL),
    TERRACOTTA_LIGHT_GREEN_HIGH(MapColorType.TERRACOTTA_LIGHT_GREEN, MapColorBrightness.HIGH),
    TERRACOTTA_LIGHT_GREEN_LOWEST(MapColorType.TERRACOTTA_LIGHT_GREEN, MapColorBrightness.LOWEST),
    TERRACOTTA_PINK_LOW(MapColorType.TERRACOTTA_PINK, MapColorBrightness.LOW),
    TERRACOTTA_PINK_NORMAL(MapColorType.TERRACOTTA_PINK, MapColorBrightness.NORMAL),
    TERRACOTTA_PINK_HIGH(MapColorType.TERRACOTTA_PINK, MapColorBrightness.HIGH),
    TERRACOTTA_PINK_LOWEST(MapColorType.TERRACOTTA_PINK, MapColorBrightness.LOWEST),
    TERRACOTTA_GRAY_LOW(MapColorType.TERRACOTTA_GRAY, MapColorBrightness.LOW),
    TERRACOTTA_GRAY_NORMAL(MapColorType.TERRACOTTA_GRAY, MapColorBrightness.NORMAL),
    TERRACOTTA_GRAY_HIGH(MapColorType.TERRACOTTA_GRAY, MapColorBrightness.HIGH),
    TERRACOTTA_GRAY_LOWEST(MapColorType.TERRACOTTA_GRAY, MapColorBrightness.LOWEST),
    TERRACOTTA_LIGHT_GRAY_LOW(MapColorType.TERRACOTTA_LIGHT_GRAY, MapColorBrightness.LOW),
    TERRACOTTA_LIGHT_GRAY_NORMAL(MapColorType.TERRACOTTA_LIGHT_GRAY, MapColorBrightness.NORMAL),
    TERRACOTTA_LIGHT_GRAY_HIGH(MapColorType.TERRACOTTA_LIGHT_GRAY, MapColorBrightness.HIGH),
    TERRACOTTA_LIGHT_GRAY_LOWEST(MapColorType.TERRACOTTA_LIGHT_GRAY, MapColorBrightness.LOWEST),
    TERRACOTTA_CYAN_LOW(MapColorType.TERRACOTTA_CYAN, MapColorBrightness.LOW),
    TERRACOTTA_CYAN_NORMAL(MapColorType.TERRACOTTA_CYAN, MapColorBrightness.NORMAL),
    TERRACOTTA_CYAN_HIGH(MapColorType.TERRACOTTA_CYAN, MapColorBrightness.HIGH),
    TERRACOTTA_CYAN_LOWEST(MapColorType.TERRACOTTA_CYAN, MapColorBrightness.LOWEST),
    TERRACOTTA_PURPLE_LOW(MapColorType.TERRACOTTA_PURPLE, MapColorBrightness.LOW),
    TERRACOTTA_PURPLE_NORMAL(MapColorType.TERRACOTTA_PURPLE, MapColorBrightness.NORMAL),
    TERRACOTTA_PURPLE_HIGH(MapColorType.TERRACOTTA_PURPLE, MapColorBrightness.HIGH),
    TERRACOTTA_PURPLE_LOWEST(MapColorType.TERRACOTTA_PURPLE, MapColorBrightness.LOWEST),
    TERRACOTTA_BLUE_LOW(MapColorType.TERRACOTTA_BLUE, MapColorBrightness.LOW),
    TERRACOTTA_BLUE_NORMAL(MapColorType.TERRACOTTA_BLUE, MapColorBrightness.NORMAL),
    TERRACOTTA_BLUE_HIGH(MapColorType.TERRACOTTA_BLUE, MapColorBrightness.HIGH),
    TERRACOTTA_BLUE_LOWEST(MapColorType.TERRACOTTA_BLUE, MapColorBrightness.LOWEST),
    TERRACOTTA_BROWN_LOW(MapColorType.TERRACOTTA_BROWN, MapColorBrightness.LOW),
    TERRACOTTA_BROWN_NORMAL(MapColorType.TERRACOTTA_BROWN, MapColorBrightness.NORMAL),
    TERRACOTTA_BROWN_HIGH(MapColorType.TERRACOTTA_BROWN, MapColorBrightness.HIGH),
    TERRACOTTA_BROWN_LOWEST(MapColorType.TERRACOTTA_BROWN, MapColorBrightness.LOWEST),
    TERRACOTTA_GREEN_LOW(MapColorType.TERRACOTTA_GREEN, MapColorBrightness.LOW),
    TERRACOTTA_GREEN_NORMAL(MapColorType.TERRACOTTA_GREEN, MapColorBrightness.NORMAL),
    TERRACOTTA_GREEN_HIGH(MapColorType.TERRACOTTA_GREEN, MapColorBrightness.HIGH),
    TERRACOTTA_GREEN_LOWEST(MapColorType.TERRACOTTA_GREEN, MapColorBrightness.LOWEST),
    TERRACOTTA_RED_LOW(MapColorType.TERRACOTTA_RED, MapColorBrightness.LOW),
    TERRACOTTA_RED_NORMAL(MapColorType.TERRACOTTA_RED, MapColorBrightness.NORMAL),
    TERRACOTTA_RED_HIGH(MapColorType.TERRACOTTA_RED, MapColorBrightness.HIGH),
    TERRACOTTA_RED_LOWEST(MapColorType.TERRACOTTA_RED, MapColorBrightness.LOWEST),
    TERRACOTTA_BLACK_LOW(MapColorType.TERRACOTTA_BLACK, MapColorBrightness.LOW),
    TERRACOTTA_BLACK_NORMAL(MapColorType.TERRACOTTA_BLACK, MapColorBrightness.NORMAL),
    TERRACOTTA_BLACK_HIGH(MapColorType.TERRACOTTA_BLACK, MapColorBrightness.HIGH),
    TERRACOTTA_BLACK_LOWEST(MapColorType.TERRACOTTA_BLACK, MapColorBrightness.LOWEST),
    CRIMSON_NYLIUM_LOW(MapColorType.CRIMSON_NYLIUM, MapColorBrightness.LOW),
    CRIMSON_NYLIUM_NORMAL(MapColorType.CRIMSON_NYLIUM, MapColorBrightness.NORMAL),
    CRIMSON_NYLIUM_HIGH(MapColorType.CRIMSON_NYLIUM, MapColorBrightness.HIGH),
    CRIMSON_NYLIUM_LOWEST(MapColorType.CRIMSON_NYLIUM, MapColorBrightness.LOWEST),
    CRIMSON_STEM_LOW(MapColorType.CRIMSON_STEM, MapColorBrightness.LOW),
    CRIMSON_STEM_NORMAL(MapColorType.CRIMSON_STEM, MapColorBrightness.NORMAL),
    CRIMSON_STEM_HIGH(MapColorType.CRIMSON_STEM, MapColorBrightness.HIGH),
    CRIMSON_STEM_LOWEST(MapColorType.CRIMSON_STEM, MapColorBrightness.LOWEST),
    CRIMSON_HYPHAE_LOW(MapColorType.CRIMSON_HYPHAE, MapColorBrightness.LOW),
    CRIMSON_HYPHAE_NORMAL(MapColorType.CRIMSON_HYPHAE, MapColorBrightness.NORMAL),
    CRIMSON_HYPHAE_HIGH(MapColorType.CRIMSON_HYPHAE, MapColorBrightness.HIGH),
    CRIMSON_HYPHAE_LOWEST(MapColorType.CRIMSON_HYPHAE, MapColorBrightness.LOWEST),
    WARPED_NYLIUM_LOW(MapColorType.WARPED_NYLIUM, MapColorBrightness.LOW),
    WARPED_NYLIUM_NORMAL(MapColorType.WARPED_NYLIUM, MapColorBrightness.NORMAL),
    WARPED_NYLIUM_HIGH(MapColorType.WARPED_NYLIUM, MapColorBrightness.HIGH),
    WARPED_NYLIUM_LOWEST(MapColorType.WARPED_NYLIUM, MapColorBrightness.LOWEST),
    WARPED_STEM_LOW(MapColorType.WARPED_STEM, MapColorBrightness.LOW),
    WARPED_STEM_NORMAL(MapColorType.WARPED_STEM, MapColorBrightness.NORMAL),
    WARPED_STEM_HIGH(MapColorType.WARPED_STEM, MapColorBrightness.HIGH),
    WARPED_STEM_LOWEST(MapColorType.WARPED_STEM, MapColorBrightness.LOWEST),
    WARPED_HYPHAE_LOW(MapColorType.WARPED_HYPHAE, MapColorBrightness.LOW),
    WARPED_HYPHAE_NORMAL(MapColorType.WARPED_HYPHAE, MapColorBrightness.NORMAL),
    WARPED_HYPHAE_HIGH(MapColorType.WARPED_HYPHAE, MapColorBrightness.HIGH),
    WARPED_HYPHAE_LOWEST(MapColorType.WARPED_HYPHAE, MapColorBrightness.LOWEST),
    WARPED_WART_BLOCK_LOW(MapColorType.WARPED_WART_BLOCK, MapColorBrightness.LOW),
    WARPED_WART_BLOCK_NORMAL(MapColorType.WARPED_WART_BLOCK, MapColorBrightness.NORMAL),
    WARPED_WART_BLOCK_HIGH(MapColorType.WARPED_WART_BLOCK, MapColorBrightness.HIGH),
    WARPED_WART_BLOCK_LOWEST(MapColorType.WARPED_WART_BLOCK, MapColorBrightness.LOWEST),
    DEEPSLATE_LOW(MapColorType.DEEPSLATE, MapColorBrightness.LOW),
    DEEPSLATE_NORMAL(MapColorType.DEEPSLATE, MapColorBrightness.NORMAL),
    DEEPSLATE_HIGH(MapColorType.DEEPSLATE, MapColorBrightness.HIGH),
    DEEPSLATE_LOWEST(MapColorType.DEEPSLATE, MapColorBrightness.LOWEST),
    RAW_IRON_LOW(MapColorType.RAW_IRON, MapColorBrightness.LOW),
    RAW_IRON_NORMAL(MapColorType.RAW_IRON, MapColorBrightness.NORMAL),
    RAW_IRON_HIGH(MapColorType.RAW_IRON, MapColorBrightness.HIGH),
    RAW_IRON_LOWEST(MapColorType.RAW_IRON, MapColorBrightness.LOWEST),
    GLOW_LICHEN_LOW(MapColorType.GLOW_LICHEN, MapColorBrightness.LOW),
    GLOW_LICHEN_NORMAL(MapColorType.GLOW_LICHEN, MapColorBrightness.NORMAL),
    GLOW_LICHEN_HIGH(MapColorType.GLOW_LICHEN, MapColorBrightness.HIGH),
    GLOW_LICHEN_LOWEST(MapColorType.GLOW_LICHEN, MapColorBrightness.LOWEST);

    /**
     * The RGB colour represented by this colour.
     */
    @get:JvmName("color")
    public val color: Color = Color(
        type.color.red * brightness.modifier / 255,
        type.color.green * brightness.modifier / 255,
        type.color.blue * brightness.modifier / 255
    )
}
