/*
 * This file is part of the Krypton project, licensed under the GNU General Public License v3.0
 *
 * Copyright (C) 2021 KryptonMC and the contributors of the Krypton project
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.kryptonmc.krypton.util.converters

import ca.spottedleaf.dataconverter.types.MapType
import org.kryptonmc.krypton.util.converter.MCVersions
import org.kryptonmc.krypton.util.converter.StringDataConverter
import org.kryptonmc.krypton.util.converter.types.nbt.NBTTypeUtil
import org.kryptonmc.krypton.util.logger

object ItemStackFlatteningConverter : StringDataConverter(MCVersions.V17W47A, 4) {

    private val LOGGER = logger<ItemStackFlatteningConverter>()
    private val FLATTEN_MAP = mapOf(
        "minecraft:stone.0" to "minecraft:stone",
        "minecraft:stone.1" to "minecraft:granite",
        "minecraft:stone.2" to "minecraft:polished_granite",
        "minecraft:stone.3" to "minecraft:diorite",
        "minecraft:stone.4" to "minecraft:polished_diorite",
        "minecraft:stone.5" to "minecraft:andesite",
        "minecraft:stone.6" to "minecraft:polished_andesite",
        "minecraft:dirt.0" to "minecraft:dirt",
        "minecraft:dirt.1" to "minecraft:coarse_dirt",
        "minecraft:dirt.2" to "minecraft:podzol",
        "minecraft:leaves.0" to "minecraft:oak_leaves",
        "minecraft:leaves.1" to "minecraft:spruce_leaves",
        "minecraft:leaves.2" to "minecraft:birch_leaves",
        "minecraft:leaves.3" to "minecraft:jungle_leaves",
        "minecraft:leaves2.0" to "minecraft:acacia_leaves",
        "minecraft:leaves2.1" to "minecraft:dark_oak_leaves",
        "minecraft:log.0" to "minecraft:oak_log",
        "minecraft:log.1" to "minecraft:spruce_log",
        "minecraft:log.2" to "minecraft:birch_log",
        "minecraft:log.3" to "minecraft:jungle_log",
        "minecraft:log2.0" to "minecraft:acacia_log",
        "minecraft:log2.1" to "minecraft:dark_oak_log",
        "minecraft:sapling.0" to "minecraft:oak_sapling",
        "minecraft:sapling.1" to "minecraft:spruce_sapling",
        "minecraft:sapling.2" to "minecraft:birch_sapling",
        "minecraft:sapling.3" to "minecraft:jungle_sapling",
        "minecraft:sapling.4" to "minecraft:acacia_sapling",
        "minecraft:sapling.5" to "minecraft:dark_oak_sapling",
        "minecraft:planks.0" to "minecraft:oak_planks",
        "minecraft:planks.1" to "minecraft:spruce_planks",
        "minecraft:planks.2" to "minecraft:birch_planks",
        "minecraft:planks.3" to "minecraft:jungle_planks",
        "minecraft:planks.4" to "minecraft:acacia_planks",
        "minecraft:planks.5" to "minecraft:dark_oak_planks",
        "minecraft:sand.0" to "minecraft:sand",
        "minecraft:sand.1" to "minecraft:red_sand",
        "minecraft:quartz_block.0" to "minecraft:quartz_block",
        "minecraft:quartz_block.1" to "minecraft:chiseled_quartz_block",
        "minecraft:quartz_block.2" to "minecraft:quartz_pillar",
        "minecraft:anvil.0" to "minecraft:anvil",
        "minecraft:anvil.1" to "minecraft:chipped_anvil",
        "minecraft:anvil.2" to "minecraft:damaged_anvil",
        "minecraft:wool.0" to "minecraft:white_wool",
        "minecraft:wool.1" to "minecraft:orange_wool",
        "minecraft:wool.2" to "minecraft:magenta_wool",
        "minecraft:wool.3" to "minecraft:light_blue_wool",
        "minecraft:wool.4" to "minecraft:yellow_wool",
        "minecraft:wool.5" to "minecraft:lime_wool",
        "minecraft:wool.6" to "minecraft:pink_wool",
        "minecraft:wool.7" to "minecraft:gray_wool",
        "minecraft:wool.8" to "minecraft:light_gray_wool",
        "minecraft:wool.9" to "minecraft:cyan_wool",
        "minecraft:wool.10" to "minecraft:purple_wool",
        "minecraft:wool.11" to "minecraft:blue_wool",
        "minecraft:wool.12" to "minecraft:brown_wool",
        "minecraft:wool.13" to "minecraft:green_wool",
        "minecraft:wool.14" to "minecraft:red_wool",
        "minecraft:wool.15" to "minecraft:black_wool",
        "minecraft:carpet.0" to "minecraft:white_carpet",
        "minecraft:carpet.1" to "minecraft:orange_carpet",
        "minecraft:carpet.2" to "minecraft:magenta_carpet",
        "minecraft:carpet.3" to "minecraft:light_blue_carpet",
        "minecraft:carpet.4" to "minecraft:yellow_carpet",
        "minecraft:carpet.5" to "minecraft:lime_carpet",
        "minecraft:carpet.6" to "minecraft:pink_carpet",
        "minecraft:carpet.7" to "minecraft:gray_carpet",
        "minecraft:carpet.8" to "minecraft:light_gray_carpet",
        "minecraft:carpet.9" to "minecraft:cyan_carpet",
        "minecraft:carpet.10" to "minecraft:purple_carpet",
        "minecraft:carpet.11" to "minecraft:blue_carpet",
        "minecraft:carpet.12" to "minecraft:brown_carpet",
        "minecraft:carpet.13" to "minecraft:green_carpet",
        "minecraft:carpet.14" to "minecraft:red_carpet",
        "minecraft:carpet.15" to "minecraft:black_carpet",
        "minecraft:hardened_clay.0" to "minecraft:terracotta",
        "minecraft:stained_hardened_clay.0" to "minecraft:white_terracotta",
        "minecraft:stained_hardened_clay.1" to "minecraft:orange_terracotta",
        "minecraft:stained_hardened_clay.2" to "minecraft:magenta_terracotta",
        "minecraft:stained_hardened_clay.3" to "minecraft:light_blue_terracotta",
        "minecraft:stained_hardened_clay.4" to "minecraft:yellow_terracotta",
        "minecraft:stained_hardened_clay.5" to "minecraft:lime_terracotta",
        "minecraft:stained_hardened_clay.6" to "minecraft:pink_terracotta",
        "minecraft:stained_hardened_clay.7" to "minecraft:gray_terracotta",
        "minecraft:stained_hardened_clay.8" to "minecraft:light_gray_terracotta",
        "minecraft:stained_hardened_clay.9" to "minecraft:cyan_terracotta",
        "minecraft:stained_hardened_clay.10" to "minecraft:purple_terracotta",
        "minecraft:stained_hardened_clay.11" to "minecraft:blue_terracotta",
        "minecraft:stained_hardened_clay.12" to "minecraft:brown_terracotta",
        "minecraft:stained_hardened_clay.13" to "minecraft:green_terracotta",
        "minecraft:stained_hardened_clay.14" to "minecraft:red_terracotta",
        "minecraft:stained_hardened_clay.15" to "minecraft:black_terracotta",
        "minecraft:silver_glazed_terracotta.0" to "minecraft:light_gray_glazed_terracotta",
        "minecraft:stained_glass.0" to "minecraft:white_stained_glass",
        "minecraft:stained_glass.1" to "minecraft:orange_stained_glass",
        "minecraft:stained_glass.2" to "minecraft:magenta_stained_glass",
        "minecraft:stained_glass.3" to "minecraft:light_blue_stained_glass",
        "minecraft:stained_glass.4" to "minecraft:yellow_stained_glass",
        "minecraft:stained_glass.5" to "minecraft:lime_stained_glass",
        "minecraft:stained_glass.6" to "minecraft:pink_stained_glass",
        "minecraft:stained_glass.7" to "minecraft:gray_stained_glass",
        "minecraft:stained_glass.8" to "minecraft:light_gray_stained_glass",
        "minecraft:stained_glass.9" to "minecraft:cyan_stained_glass",
        "minecraft:stained_glass.10" to "minecraft:purple_stained_glass",
        "minecraft:stained_glass.11" to "minecraft:blue_stained_glass",
        "minecraft:stained_glass.12" to "minecraft:brown_stained_glass",
        "minecraft:stained_glass.13" to "minecraft:green_stained_glass",
        "minecraft:stained_glass.14" to "minecraft:red_stained_glass",
        "minecraft:stained_glass.15" to "minecraft:black_stained_glass",
        "minecraft:stained_glass_pane.0" to "minecraft:white_stained_glass_pane",
        "minecraft:stained_glass_pane.1" to "minecraft:orange_stained_glass_pane",
        "minecraft:stained_glass_pane.2" to "minecraft:magenta_stained_glass_pane",
        "minecraft:stained_glass_pane.3" to "minecraft:light_blue_stained_glass_pane",
        "minecraft:stained_glass_pane.4" to "minecraft:yellow_stained_glass_pane",
        "minecraft:stained_glass_pane.5" to "minecraft:lime_stained_glass_pane",
        "minecraft:stained_glass_pane.6" to "minecraft:pink_stained_glass_pane",
        "minecraft:stained_glass_pane.7" to "minecraft:gray_stained_glass_pane",
        "minecraft:stained_glass_pane.8" to "minecraft:light_gray_stained_glass_pane",
        "minecraft:stained_glass_pane.9" to "minecraft:cyan_stained_glass_pane",
        "minecraft:stained_glass_pane.10" to "minecraft:purple_stained_glass_pane",
        "minecraft:stained_glass_pane.11" to "minecraft:blue_stained_glass_pane",
        "minecraft:stained_glass_pane.12" to "minecraft:brown_stained_glass_pane",
        "minecraft:stained_glass_pane.13" to "minecraft:green_stained_glass_pane",
        "minecraft:stained_glass_pane.14" to "minecraft:red_stained_glass_pane",
        "minecraft:stained_glass_pane.15" to "minecraft:black_stained_glass_pane",
        "minecraft:prismarine.0" to "minecraft:prismarine",
        "minecraft:prismarine.1" to "minecraft:prismarine_bricks",
        "minecraft:prismarine.2" to "minecraft:dark_prismarine",
        "minecraft:concrete.0" to "minecraft:white_concrete",
        "minecraft:concrete.1" to "minecraft:orange_concrete",
        "minecraft:concrete.2" to "minecraft:magenta_concrete",
        "minecraft:concrete.3" to "minecraft:light_blue_concrete",
        "minecraft:concrete.4" to "minecraft:yellow_concrete",
        "minecraft:concrete.5" to "minecraft:lime_concrete",
        "minecraft:concrete.6" to "minecraft:pink_concrete",
        "minecraft:concrete.7" to "minecraft:gray_concrete",
        "minecraft:concrete.8" to "minecraft:light_gray_concrete",
        "minecraft:concrete.9" to "minecraft:cyan_concrete",
        "minecraft:concrete.10" to "minecraft:purple_concrete",
        "minecraft:concrete.11" to "minecraft:blue_concrete",
        "minecraft:concrete.12" to "minecraft:brown_concrete",
        "minecraft:concrete.13" to "minecraft:green_concrete",
        "minecraft:concrete.14" to "minecraft:red_concrete",
        "minecraft:concrete.15" to "minecraft:black_concrete",
        "minecraft:concrete_powder.0" to "minecraft:white_concrete_powder",
        "minecraft:concrete_powder.1" to "minecraft:orange_concrete_powder",
        "minecraft:concrete_powder.2" to "minecraft:magenta_concrete_powder",
        "minecraft:concrete_powder.3" to "minecraft:light_blue_concrete_powder",
        "minecraft:concrete_powder.4" to "minecraft:yellow_concrete_powder",
        "minecraft:concrete_powder.5" to "minecraft:lime_concrete_powder",
        "minecraft:concrete_powder.6" to "minecraft:pink_concrete_powder",
        "minecraft:concrete_powder.7" to "minecraft:gray_concrete_powder",
        "minecraft:concrete_powder.8" to "minecraft:light_gray_concrete_powder",
        "minecraft:concrete_powder.9" to "minecraft:cyan_concrete_powder",
        "minecraft:concrete_powder.10" to "minecraft:purple_concrete_powder",
        "minecraft:concrete_powder.11" to "minecraft:blue_concrete_powder",
        "minecraft:concrete_powder.12" to "minecraft:brown_concrete_powder",
        "minecraft:concrete_powder.13" to "minecraft:green_concrete_powder",
        "minecraft:concrete_powder.14" to "minecraft:red_concrete_powder",
        "minecraft:concrete_powder.15" to "minecraft:black_concrete_powder",
        "minecraft:cobblestone_wall.0" to "minecraft:cobblestone_wall",
        "minecraft:cobblestone_wall.1" to "minecraft:mossy_cobblestone_wall",
        "minecraft:sandstone.0" to "minecraft:sandstone",
        "minecraft:sandstone.1" to "minecraft:chiseled_sandstone",
        "minecraft:sandstone.2" to "minecraft:cut_sandstone",
        "minecraft:red_sandstone.0" to "minecraft:red_sandstone",
        "minecraft:red_sandstone.1" to "minecraft:chiseled_red_sandstone",
        "minecraft:red_sandstone.2" to "minecraft:cut_red_sandstone",
        "minecraft:stonebrick.0" to "minecraft:stone_bricks",
        "minecraft:stonebrick.1" to "minecraft:mossy_stone_bricks",
        "minecraft:stonebrick.2" to "minecraft:cracked_stone_bricks",
        "minecraft:stonebrick.3" to "minecraft:chiseled_stone_bricks",
        "minecraft:monster_egg.0" to "minecraft:infested_stone",
        "minecraft:monster_egg.1" to "minecraft:infested_cobblestone",
        "minecraft:monster_egg.2" to "minecraft:infested_stone_bricks",
        "minecraft:monster_egg.3" to "minecraft:infested_mossy_stone_bricks",
        "minecraft:monster_egg.4" to "minecraft:infested_cracked_stone_bricks",
        "minecraft:monster_egg.5" to "minecraft:infested_chiseled_stone_bricks",
        "minecraft:yellow_flower.0" to "minecraft:dandelion",
        "minecraft:red_flower.0" to "minecraft:poppy",
        "minecraft:red_flower.1" to "minecraft:blue_orchid",
        "minecraft:red_flower.2" to "minecraft:allium",
        "minecraft:red_flower.3" to "minecraft:azure_bluet",
        "minecraft:red_flower.4" to "minecraft:red_tulip",
        "minecraft:red_flower.5" to "minecraft:orange_tulip",
        "minecraft:red_flower.6" to "minecraft:white_tulip",
        "minecraft:red_flower.7" to "minecraft:pink_tulip",
        "minecraft:red_flower.8" to "minecraft:oxeye_daisy",
        "minecraft:double_plant.0" to "minecraft:sunflower",
        "minecraft:double_plant.1" to "minecraft:lilac",
        "minecraft:double_plant.2" to "minecraft:tall_grass",
        "minecraft:double_plant.3" to "minecraft:large_fern",
        "minecraft:double_plant.4" to "minecraft:rose_bush",
        "minecraft:double_plant.5" to "minecraft:peony",
        "minecraft:deadbush.0" to "minecraft:dead_bush",
        "minecraft:tallgrass.0" to "minecraft:dead_bush",
        "minecraft:tallgrass.1" to "minecraft:grass",
        "minecraft:tallgrass.2" to "minecraft:fern",
        "minecraft:sponge.0" to "minecraft:sponge",
        "minecraft:sponge.1" to "minecraft:wet_sponge",
        "minecraft:purpur_slab.0" to "minecraft:purpur_slab",
        "minecraft:stone_slab.0" to "minecraft:stone_slab",
        "minecraft:stone_slab.1" to "minecraft:sandstone_slab",
        "minecraft:stone_slab.2" to "minecraft:petrified_oak_slab",
        "minecraft:stone_slab.3" to "minecraft:cobblestone_slab",
        "minecraft:stone_slab.4" to "minecraft:brick_slab",
        "minecraft:stone_slab.5" to "minecraft:stone_brick_slab",
        "minecraft:stone_slab.6" to "minecraft:nether_brick_slab",
        "minecraft:stone_slab.7" to "minecraft:quartz_slab",
        "minecraft:stone_slab2.0" to "minecraft:red_sandstone_slab",
        "minecraft:wooden_slab.0" to "minecraft:oak_slab",
        "minecraft:wooden_slab.1" to "minecraft:spruce_slab",
        "minecraft:wooden_slab.2" to "minecraft:birch_slab",
        "minecraft:wooden_slab.3" to "minecraft:jungle_slab",
        "minecraft:wooden_slab.4" to "minecraft:acacia_slab",
        "minecraft:wooden_slab.5" to "minecraft:dark_oak_slab",
        "minecraft:coal.0" to "minecraft:coal",
        "minecraft:coal.1" to "minecraft:charcoal",
        "minecraft:fish.0" to "minecraft:cod",
        "minecraft:fish.1" to "minecraft:salmon",
        "minecraft:fish.2" to "minecraft:clownfish",
        "minecraft:fish.3" to "minecraft:pufferfish",
        "minecraft:cooked_fish.0" to "minecraft:cooked_cod",
        "minecraft:cooked_fish.1" to "minecraft:cooked_salmon",
        "minecraft:skull.0" to "minecraft:skeleton_skull",
        "minecraft:skull.1" to "minecraft:wither_skeleton_skull",
        "minecraft:skull.2" to "minecraft:zombie_head",
        "minecraft:skull.3" to "minecraft:player_head",
        "minecraft:skull.4" to "minecraft:creeper_head",
        "minecraft:skull.5" to "minecraft:dragon_head",
        "minecraft:golden_apple.0" to "minecraft:golden_apple",
        "minecraft:golden_apple.1" to "minecraft:enchanted_golden_apple",
        "minecraft:fireworks.0" to "minecraft:firework_rocket",
        "minecraft:firework_charge.0" to "minecraft:firework_star",
        "minecraft:dye.0" to "minecraft:ink_sac",
        "minecraft:dye.1" to "minecraft:rose_red",
        "minecraft:dye.2" to "minecraft:cactus_green",
        "minecraft:dye.3" to "minecraft:cocoa_beans",
        "minecraft:dye.4" to "minecraft:lapis_lazuli",
        "minecraft:dye.5" to "minecraft:purple_dye",
        "minecraft:dye.6" to "minecraft:cyan_dye",
        "minecraft:dye.7" to "minecraft:light_gray_dye",
        "minecraft:dye.8" to "minecraft:gray_dye",
        "minecraft:dye.9" to "minecraft:pink_dye",
        "minecraft:dye.10" to "minecraft:lime_dye",
        "minecraft:dye.11" to "minecraft:dandelion_yellow",
        "minecraft:dye.12" to "minecraft:light_blue_dye",
        "minecraft:dye.13" to "minecraft:magenta_dye",
        "minecraft:dye.14" to "minecraft:orange_dye",
        "minecraft:dye.15" to "minecraft:bone_meal",
        "minecraft:silver_shulker_box.0" to "minecraft:light_gray_shulker_box",
        "minecraft:fence.0" to "minecraft:oak_fence",
        "minecraft:fence_gate.0" to "minecraft:oak_fence_gate",
        "minecraft:wooden_door.0" to "minecraft:oak_door",
        "minecraft:boat.0" to "minecraft:oak_boat",
        "minecraft:lit_pumpkin.0" to "minecraft:jack_o_lantern",
        "minecraft:pumpkin.0" to "minecraft:carved_pumpkin",
        "minecraft:trapdoor.0" to "minecraft:oak_trapdoor",
        "minecraft:nether_brick.0" to "minecraft:nether_bricks",
        "minecraft:red_nether_brick.0" to "minecraft:red_nether_bricks",
        "minecraft:netherbrick.0" to "minecraft:nether_brick",
        "minecraft:wooden_button.0" to "minecraft:oak_button",
        "minecraft:wooden_pressure_plate.0" to "minecraft:oak_pressure_plate",
        "minecraft:noteblock.0" to "minecraft:note_block",
        "minecraft:bed.0" to "minecraft:white_bed",
        "minecraft:bed.1" to "minecraft:orange_bed",
        "minecraft:bed.2" to "minecraft:magenta_bed",
        "minecraft:bed.3" to "minecraft:light_blue_bed",
        "minecraft:bed.4" to "minecraft:yellow_bed",
        "minecraft:bed.5" to "minecraft:lime_bed",
        "minecraft:bed.6" to "minecraft:pink_bed",
        "minecraft:bed.7" to "minecraft:gray_bed",
        "minecraft:bed.8" to "minecraft:light_gray_bed",
        "minecraft:bed.9" to "minecraft:cyan_bed",
        "minecraft:bed.10" to "minecraft:purple_bed",
        "minecraft:bed.11" to "minecraft:blue_bed",
        "minecraft:bed.12" to "minecraft:brown_bed",
        "minecraft:bed.13" to "minecraft:green_bed",
        "minecraft:bed.14" to "minecraft:red_bed",
        "minecraft:bed.15" to "minecraft:black_bed",
        "minecraft:banner.15" to "minecraft:white_banner",
        "minecraft:banner.14" to "minecraft:orange_banner",
        "minecraft:banner.13" to "minecraft:magenta_banner",
        "minecraft:banner.12" to "minecraft:light_blue_banner",
        "minecraft:banner.11" to "minecraft:yellow_banner",
        "minecraft:banner.10" to "minecraft:lime_banner",
        "minecraft:banner.9" to "minecraft:pink_banner",
        "minecraft:banner.8" to "minecraft:gray_banner",
        "minecraft:banner.7" to "minecraft:light_gray_banner",
        "minecraft:banner.6" to "minecraft:cyan_banner",
        "minecraft:banner.5" to "minecraft:purple_banner",
        "minecraft:banner.4" to "minecraft:blue_banner",
        "minecraft:banner.3" to "minecraft:brown_banner",
        "minecraft:banner.2" to "minecraft:green_banner",
        "minecraft:banner.1" to "minecraft:red_banner",
        "minecraft:banner.0" to "minecraft:black_banner",
        "minecraft:grass.0" to "minecraft:grass_block",
        "minecraft:brick_block.0" to "minecraft:bricks",
        "minecraft:end_bricks.0" to "minecraft:end_stone_bricks",
        "minecraft:golden_rail.0" to "minecraft:powered_rail",
        "minecraft:magma.0" to "minecraft:magma_block",
        "minecraft:quartz_ore.0" to "minecraft:nether_quartz_ore",
        "minecraft:reeds.0" to "minecraft:sugar_cane",
        "minecraft:slime.0" to "minecraft:slime_block",
        "minecraft:stone_stairs.0" to "minecraft:cobblestone_stairs",
        "minecraft:waterlily.0" to "minecraft:lily_pad",
        "minecraft:web.0" to "minecraft:cobweb",
        "minecraft:snow.0" to "minecraft:snow_block",
        "minecraft:snow_layer.0" to "minecraft:snow",
        "minecraft:record_11.0" to "minecraft:music_disc_11",
        "minecraft:record_13.0" to "minecraft:music_disc_13",
        "minecraft:record_blocks.0" to "minecraft:music_disc_blocks",
        "minecraft:record_cat.0" to "minecraft:music_disc_cat",
        "minecraft:record_chirp.0" to "minecraft:music_disc_chirp",
        "minecraft:record_far.0" to "minecraft:music_disc_far",
        "minecraft:record_mall.0" to "minecraft:music_disc_mall",
        "minecraft:record_mellohi.0" to "minecraft:music_disc_mellohi",
        "minecraft:record_stal.0" to "minecraft:music_disc_stal",
        "minecraft:record_strad.0" to "minecraft:music_disc_strad",
        "minecraft:record_wait.0" to "minecraft:music_disc_wait",
        "minecraft:record_ward.0" to "minecraft:music_disc_ward",
    )
    private val IDS_REQUIRING_FLATTENING = HashSet<String>().apply {
        FLATTEN_MAP.keys.forEach {
            add(it.substring(0, it.indexOf('.')))
        }
    }
    private val ITEMS_WITH_DAMAGE = setOf(
        "minecraft:bow",
        "minecraft:carrot_on_a_stick",
        "minecraft:chainmail_boots",
        "minecraft:chainmail_chestplate",
        "minecraft:chainmail_helmet",
        "minecraft:chainmail_leggings",
        "minecraft:diamond_axe",
        "minecraft:diamond_boots",
        "minecraft:diamond_chestplate",
        "minecraft:diamond_helmet",
        "minecraft:diamond_hoe",
        "minecraft:diamond_leggings",
        "minecraft:diamond_pickaxe",
        "minecraft:diamond_shovel",
        "minecraft:diamond_sword",
        "minecraft:elytra",
        "minecraft:fishing_rod",
        "minecraft:flint_and_steel",
        "minecraft:golden_axe",
        "minecraft:golden_boots",
        "minecraft:golden_chestplate",
        "minecraft:golden_helmet",
        "minecraft:golden_hoe",
        "minecraft:golden_leggings",
        "minecraft:golden_pickaxe",
        "minecraft:golden_shovel",
        "minecraft:golden_sword",
        "minecraft:iron_axe",
        "minecraft:iron_boots",
        "minecraft:iron_chestplate",
        "minecraft:iron_helmet",
        "minecraft:iron_hoe",
        "minecraft:iron_leggings",
        "minecraft:iron_pickaxe",
        "minecraft:iron_shovel",
        "minecraft:iron_sword",
        "minecraft:leather_boots",
        "minecraft:leather_chestplate",
        "minecraft:leather_helmet",
        "minecraft:leather_leggings",
        "minecraft:shears",
        "minecraft:shield",
        "minecraft:stone_axe",
        "minecraft:stone_hoe",
        "minecraft:stone_pickaxe",
        "minecraft:stone_shovel",
        "minecraft:stone_sword",
        "minecraft:wooden_axe",
        "minecraft:wooden_hoe",
        "minecraft:wooden_pickaxe",
        "minecraft:wooden_shovel",
        "minecraft:wooden_sword"
    )

    fun flattenItem(oldName: String, data: Int): String? = if (IDS_REQUIRING_FLATTENING.contains(oldName)) {
        FLATTEN_MAP["$oldName.$data"] ?: FLATTEN_MAP["$oldName.0"]
    } else {
        null
    }

    override fun convert(data: MapType<String>, sourceVersion: Long, toVersion: Long): MapType<String>? {
        val id = data.getString("id") ?: return null
        val damage = data.getInt("Damage")
        data.remove("Damage")

        if (IDS_REQUIRING_FLATTENING.contains(id)) {
            val remap = FLATTEN_MAP["$id.$damage"] ?: FLATTEN_MAP["$id.0"]
            if (remap != null) {
                data.setString("id", remap)
            } else {
                LOGGER.warn("Item '$id' requires flattening but found no mapping for it! (ConverterFlattenItemStack)")
            }
        }

        if (damage != 0 && ITEMS_WITH_DAMAGE.contains(id)) {
            val tag = data.getMap("tag") ?: NBTTypeUtil.createEmptyMap<String>().apply { data.setMap("tag", this) }
            tag.setInt("Damage", damage)
        }
        return null
    }
}
