/*
 * This file is part of the Krypton API, licensed under the MIT license.
 *
 * Copyright (C) 2021 KryptonMC and the contributors to the Krypton project.
 *
 * This project is licensed under the terms of the MIT license.
 * For more details, please reference the LICENSE file in the api top-level directory.
 */
package org.kryptonmc.api.item

import net.kyori.adventure.key.Key
import net.kyori.adventure.text.Component
import org.kryptonmc.api.registry.Registries

/**
 * An object containing all built-in item types.
 */
@Suppress("LargeClass", "UndocumentedPublicProperty")
public object ItemTypes {

    // @formatter:off
    @JvmField public val AIR: ItemType = register("air")
    @JvmField public val STONE: ItemType = register("stone")
    @JvmField public val GRANITE: ItemType = register("granite")
    @JvmField public val POLISHED_GRANITE: ItemType = register("polished_granite")
    @JvmField public val DIORITE: ItemType = register("diorite")
    @JvmField public val POLISHED_DIORITE: ItemType = register("polished_diorite")
    @JvmField public val ANDESITE: ItemType = register("andesite")
    @JvmField public val POLISHED_ANDESITE: ItemType = register("polished_andesite")
    @JvmField public val DEEPSLATE: ItemType = register("deepslate")
    @JvmField public val COBBLED_DEEPSLATE: ItemType = register("cobbled_deepslate")
    @JvmField public val POLISHED_DEEPSLATE: ItemType = register("polished_deepslate")
    @JvmField public val CALCITE: ItemType = register("calcite")
    @JvmField public val TUFF: ItemType = register("tuff")
    @JvmField public val DRIPSTONE_BLOCK: ItemType = register("dripstone_block")
    @JvmField public val GRASS_BLOCK: ItemType = register("grass_block")
    @JvmField public val DIRT: ItemType = register("dirt")
    @JvmField public val COARSE_DIRT: ItemType = register("coarse_dirt")
    @JvmField public val PODZOL: ItemType = register("podzol")
    @JvmField public val ROOTED_DIRT: ItemType = register("rooted_dirt")
    @JvmField public val CRIMSON_NYLIUM: ItemType = register("crimson_nylium")
    @JvmField public val WARPED_NYLIUM: ItemType = register("warped_nylium")
    @JvmField public val COBBLESTONE: ItemType = register("cobblestone")
    @JvmField public val OAK_PLANKS: ItemType = register("oak_planks")
    @JvmField public val SPRUCE_PLANKS: ItemType = register("spruce_planks")
    @JvmField public val BIRCH_PLANKS: ItemType = register("birch_planks")
    @JvmField public val JUNGLE_PLANKS: ItemType = register("jungle_planks")
    @JvmField public val ACACIA_PLANKS: ItemType = register("acacia_planks")
    @JvmField public val DARK_OAK_PLANKS: ItemType = register("dark_oak_planks")
    @JvmField public val CRIMSON_PLANKS: ItemType = register("crimson_planks")
    @JvmField public val WARPED_PLANKS: ItemType = register("warped_planks")
    @JvmField public val OAK_SAPLING: ItemType = register("oak_sapling")
    @JvmField public val SPRUCE_SAPLING: ItemType = register("spruce_sapling")
    @JvmField public val BIRCH_SAPLING: ItemType = register("birch_sapling")
    @JvmField public val JUNGLE_SAPLING: ItemType = register("jungle_sapling")
    @JvmField public val ACACIA_SAPLING: ItemType = register("acacia_sapling")
    @JvmField public val DARK_OAK_SAPLING: ItemType = register("dark_oak_sapling")
    @JvmField public val BEDROCK: ItemType = register("bedrock")
    @JvmField public val SAND: ItemType = register("sand")
    @JvmField public val RED_SAND: ItemType = register("red_sand")
    @JvmField public val GRAVEL: ItemType = register("gravel")
    @JvmField public val COAL_ORE: ItemType = register("coal_ore")
    @JvmField public val DEEPSLATE_COAL_ORE: ItemType = register("deepslate_coal_ore")
    @JvmField public val IRON_ORE: ItemType = register("iron_ore")
    @JvmField public val DEEPSLATE_IRON_ORE: ItemType = register("deepslate_iron_ore")
    @JvmField public val COPPER_ORE: ItemType = register("copper_ore")
    @JvmField public val DEEPSLATE_COPPER_ORE: ItemType = register("deepslate_copper_ore")
    @JvmField public val GOLD_ORE: ItemType = register("gold_ore")
    @JvmField public val DEEPSLATE_GOLD_ORE: ItemType = register("deepslate_gold_ore")
    @JvmField public val REDSTONE_ORE: ItemType = register("redstone_ore")
    @JvmField public val DEEPSLATE_REDSTONE_ORE: ItemType = register("deepslate_redstone_ore")
    @JvmField public val EMERALD_ORE: ItemType = register("emerald_ore")
    @JvmField public val DEEPSLATE_EMERALD_ORE: ItemType = register("deepslate_emerald_ore")
    @JvmField public val LAPIS_ORE: ItemType = register("lapis_ore")
    @JvmField public val DEEPSLATE_LAPIS_ORE: ItemType = register("deepslate_lapis_ore")
    @JvmField public val DIAMOND_ORE: ItemType = register("diamond_ore")
    @JvmField public val DEEPSLATE_DIAMOND_ORE: ItemType = register("deepslate_diamond_ore")
    @JvmField public val NETHER_GOLD_ORE: ItemType = register("nether_gold_ore")
    @JvmField public val NETHER_QUARTZ_ORE: ItemType = register("nether_quartz_ore")
    @JvmField public val ANCIENT_DEBRIS: ItemType = register("ancient_debris", isFireResistant = true)
    @JvmField public val RAW_IRON_BLOCK: ItemType = register("raw_iron_block")
    @JvmField public val RAW_COPPER_BLOCK: ItemType = register("raw_copper_block")
    @JvmField public val RAW_GOLD_BLOCK: ItemType = register("raw_gold_block")
    @JvmField public val AMETHYST_BLOCK: ItemType = register("amethyst_block")
    @JvmField public val BUDDING_AMETHYST: ItemType = register("budding_amethyst")
    @JvmField public val IRON_BLOCK: ItemType = register("iron_block")
    @JvmField public val COPPER_BLOCK: ItemType = register("copper_block")
    @JvmField public val GOLD_BLOCK: ItemType = register("gold_block")
    @JvmField public val DIAMOND_BLOCK: ItemType = register("diamond_block")
    @JvmField public val NETHERITE_BLOCK: ItemType = register("netherite_block", isFireResistant = true)
    @JvmField public val EXPOSED_COPPER: ItemType = register("exposed_copper")
    @JvmField public val WEATHERED_COPPER: ItemType = register("weathered_copper")
    @JvmField public val OXIDIZED_COPPER: ItemType = register("oxidized_copper")
    @JvmField public val CUT_COPPER: ItemType = register("cut_copper")
    @JvmField public val EXPOSED_CUT_COPPER: ItemType = register("exposed_cut_copper")
    @JvmField public val WEATHERED_CUT_COPPER: ItemType = register("weathered_cut_copper")
    @JvmField public val OXIDIZED_CUT_COPPER: ItemType = register("oxidized_cut_copper")
    @JvmField public val CUT_COPPER_STAIRS: ItemType = register("cut_copper_stairs")
    @JvmField public val EXPOSED_CUT_COPPER_STAIRS: ItemType = register("exposed_cut_copper_stairs")
    @JvmField public val WEATHERED_CUT_COPPER_STAIRS: ItemType = register("weathered_cut_copper_stairs")
    @JvmField public val OXIDIZED_CUT_COPPER_STAIRS: ItemType = register("oxidized_cut_copper_stairs")
    @JvmField public val CUT_COPPER_SLAB: ItemType = register("cut_copper_slab")
    @JvmField public val EXPOSED_CUT_COPPER_SLAB: ItemType = register("exposed_cut_copper_slab")
    @JvmField public val WEATHERED_CUT_COPPER_SLAB: ItemType = register("weathered_cut_copper_slab")
    @JvmField public val OXIDIZED_CUT_COPPER_SLAB: ItemType = register("oxidized_cut_copper_slab")
    @JvmField public val WAXED_COPPER_BLOCK: ItemType = register("waxed_copper_block")
    @JvmField public val WAXED_EXPOSED_COPPER: ItemType = register("waxed_exposed_copper")
    @JvmField public val WAXED_WEATHERED_COPPER: ItemType = register("waxed_weathered_copper")
    @JvmField public val WAXED_OXIDIZED_COPPER: ItemType = register("waxed_oxidized_copper")
    @JvmField public val WAXED_CUT_COPPER: ItemType = register("waxed_cut_copper")
    @JvmField public val WAXED_EXPOSED_CUT_COPPER: ItemType = register("waxed_exposed_cut_copper")
    @JvmField public val WAXED_WEATHERED_CUT_COPPER: ItemType = register("waxed_weathered_cut_copper")
    @JvmField public val WAXED_OXIDIZED_CUT_COPPER: ItemType = register("waxed_oxidized_cut_copper")
    @JvmField public val WAXED_CUT_COPPER_STAIRS: ItemType = register("waxed_cut_copper_stairs")
    @JvmField public val WAXED_EXPOSED_CUT_COPPER_STAIRS: ItemType = register("waxed_exposed_cut_copper_stairs")
    @JvmField public val WAXED_WEATHERED_CUT_COPPER_STAIRS: ItemType = register("waxed_weathered_cut_copper_stairs")
    @JvmField public val WAXED_OXIDIZED_CUT_COPPER_STAIRS: ItemType = register("waxed_oxidized_cut_copper_stairs")
    @JvmField public val WAXED_CUT_COPPER_SLAB: ItemType = register("waxed_cut_copper_slab")
    @JvmField public val WAXED_EXPOSED_CUT_COPPER_SLAB: ItemType = register("waxed_exposed_cut_copper_slab")
    @JvmField public val WAXED_WEATHERED_CUT_COPPER_SLAB: ItemType = register("waxed_weathered_cut_copper_slab")
    @JvmField public val WAXED_OXIDIZED_CUT_COPPER_SLAB: ItemType = register("waxed_oxidized_cut_copper_slab")
    @JvmField public val OAK_LOG: ItemType = register("oak_log")
    @JvmField public val SPRUCE_LOG: ItemType = register("spruce_log")
    @JvmField public val BIRCH_LOG: ItemType = register("birch_log")
    @JvmField public val JUNGLE_LOG: ItemType = register("jungle_log")
    @JvmField public val ACACIA_LOG: ItemType = register("acacia_log")
    @JvmField public val DARK_OAK_LOG: ItemType = register("dark_oak_log")
    @JvmField public val CRIMSON_STEM: ItemType = register("crimson_stem")
    @JvmField public val WARPED_STEM: ItemType = register("warped_stem")
    @JvmField public val STRIPPED_OAK_LOG: ItemType = register("stripped_oak_log")
    @JvmField public val STRIPPED_SPRUCE_LOG: ItemType = register("stripped_spruce_log")
    @JvmField public val STRIPPED_BIRCH_LOG: ItemType = register("stripped_birch_log")
    @JvmField public val STRIPPED_JUNGLE_LOG: ItemType = register("stripped_jungle_log")
    @JvmField public val STRIPPED_ACACIA_LOG: ItemType = register("stripped_acacia_log")
    @JvmField public val STRIPPED_DARK_OAK_LOG: ItemType = register("stripped_dark_oak_log")
    @JvmField public val STRIPPED_CRIMSON_STEM: ItemType = register("stripped_crimson_stem")
    @JvmField public val STRIPPED_WARPED_STEM: ItemType = register("stripped_warped_stem")
    @JvmField public val STRIPPED_OAK_WOOD: ItemType = register("stripped_oak_wood")
    @JvmField public val STRIPPED_SPRUCE_WOOD: ItemType = register("stripped_spruce_wood")
    @JvmField public val STRIPPED_BIRCH_WOOD: ItemType = register("stripped_birch_wood")
    @JvmField public val STRIPPED_JUNGLE_WOOD: ItemType = register("stripped_jungle_wood")
    @JvmField public val STRIPPED_ACACIA_WOOD: ItemType = register("stripped_acacia_wood")
    @JvmField public val STRIPPED_DARK_OAK_WOOD: ItemType = register("stripped_dark_oak_wood")
    @JvmField public val STRIPPED_CRIMSON_HYPHAE: ItemType = register("stripped_crimson_hyphae")
    @JvmField public val STRIPPED_WARPED_HYPHAE: ItemType = register("stripped_warped_hyphae")
    @JvmField public val OAK_WOOD: ItemType = register("oak_wood")
    @JvmField public val SPRUCE_WOOD: ItemType = register("spruce_wood")
    @JvmField public val BIRCH_WOOD: ItemType = register("birch_wood")
    @JvmField public val JUNGLE_WOOD: ItemType = register("jungle_wood")
    @JvmField public val ACACIA_WOOD: ItemType = register("acacia_wood")
    @JvmField public val DARK_OAK_WOOD: ItemType = register("dark_oak_wood")
    @JvmField public val CRIMSON_HYPHAE: ItemType = register("crimson_hyphae")
    @JvmField public val WARPED_HYPHAE: ItemType = register("warped_hyphae")
    @JvmField public val OAK_LEAVES: ItemType = register("oak_leaves")
    @JvmField public val SPRUCE_LEAVES: ItemType = register("spruce_leaves")
    @JvmField public val BIRCH_LEAVES: ItemType = register("birch_leaves")
    @JvmField public val JUNGLE_LEAVES: ItemType = register("jungle_leaves")
    @JvmField public val ACACIA_LEAVES: ItemType = register("acacia_leaves")
    @JvmField public val DARK_OAK_LEAVES: ItemType = register("dark_oak_leaves")
    @JvmField public val AZALEA_LEAVES: ItemType = register("azalea_leaves")
    @JvmField public val FLOWERING_AZALEA_LEAVES: ItemType = register("flowering_azalea_leaves")
    @JvmField public val SPONGE: ItemType = register("sponge")
    @JvmField public val WET_SPONGE: ItemType = register("wet_sponge")
    @JvmField public val GLASS: ItemType = register("glass")
    @JvmField public val TINTED_GLASS: ItemType = register("tinted_glass")
    @JvmField public val LAPIS_BLOCK: ItemType = register("lapis_block")
    @JvmField public val SANDSTONE: ItemType = register("sandstone")
    @JvmField public val CHISELED_SANDSTONE: ItemType = register("chiseled_sandstone")
    @JvmField public val CUT_SANDSTONE: ItemType = register("cut_sandstone")
    @JvmField public val COBWEB: ItemType = register("cobweb")
    @JvmField public val GRASS: ItemType = register("grass")
    @JvmField public val FERN: ItemType = register("fern")
    @JvmField public val AZALEA: ItemType = register("azalea")
    @JvmField public val FLOWERING_AZALEA: ItemType = register("flowering_azalea")
    @JvmField public val DEAD_BUSH: ItemType = register("dead_bush")
    @JvmField public val SEAGRASS: ItemType = register("seagrass")
    @JvmField public val SEA_PICKLE: ItemType = register("sea_pickle")
    @JvmField public val WHITE_WOOL: ItemType = register("white_wool")
    @JvmField public val ORANGE_WOOL: ItemType = register("orange_wool")
    @JvmField public val MAGENTA_WOOL: ItemType = register("magenta_wool")
    @JvmField public val LIGHT_BLUE_WOOL: ItemType = register("light_blue_wool")
    @JvmField public val YELLOW_WOOL: ItemType = register("yellow_wool")
    @JvmField public val LIME_WOOL: ItemType = register("lime_wool")
    @JvmField public val PINK_WOOL: ItemType = register("pink_wool")
    @JvmField public val GRAY_WOOL: ItemType = register("gray_wool")
    @JvmField public val LIGHT_GRAY_WOOL: ItemType = register("light_gray_wool")
    @JvmField public val CYAN_WOOL: ItemType = register("cyan_wool")
    @JvmField public val PURPLE_WOOL: ItemType = register("purple_wool")
    @JvmField public val BLUE_WOOL: ItemType = register("blue_wool")
    @JvmField public val BROWN_WOOL: ItemType = register("brown_wool")
    @JvmField public val GREEN_WOOL: ItemType = register("green_wool")
    @JvmField public val RED_WOOL: ItemType = register("red_wool")
    @JvmField public val BLACK_WOOL: ItemType = register("black_wool")
    @JvmField public val DANDELION: ItemType = register("dandelion")
    @JvmField public val POPPY: ItemType = register("poppy")
    @JvmField public val BLUE_ORCHID: ItemType = register("blue_orchid")
    @JvmField public val ALLIUM: ItemType = register("allium")
    @JvmField public val AZURE_BLUET: ItemType = register("azure_bluet")
    @JvmField public val RED_TULIP: ItemType = register("red_tulip")
    @JvmField public val ORANGE_TULIP: ItemType = register("orange_tulip")
    @JvmField public val WHITE_TULIP: ItemType = register("white_tulip")
    @JvmField public val PINK_TULIP: ItemType = register("pink_tulip")
    @JvmField public val OXEYE_DAISY: ItemType = register("oxeye_daisy")
    @JvmField public val CORNFLOWER: ItemType = register("cornflower")
    @JvmField public val LILY_OF_THE_VALLEY: ItemType = register("lily_of_the_valley")
    @JvmField public val WITHER_ROSE: ItemType = register("wither_rose")
    @JvmField public val SPORE_BLOSSOM: ItemType = register("spore_blossom")
    @JvmField public val BROWN_MUSHROOM: ItemType = register("brown_mushroom")
    @JvmField public val RED_MUSHROOM: ItemType = register("red_mushroom")
    @JvmField public val CRIMSON_FUNGUS: ItemType = register("crimson_fungus")
    @JvmField public val WARPED_FUNGUS: ItemType = register("warped_fungus")
    @JvmField public val CRIMSON_ROOTS: ItemType = register("crimson_roots")
    @JvmField public val WARPED_ROOTS: ItemType = register("warped_roots")
    @JvmField public val NETHER_SPROUTS: ItemType = register("nether_sprouts")
    @JvmField public val WEEPING_VINES: ItemType = register("weeping_vines")
    @JvmField public val TWISTING_VINES: ItemType = register("twisting_vines")
    @JvmField public val SUGAR_CANE: ItemType = register("sugar_cane")
    @JvmField public val KELP: ItemType = register("kelp")
    @JvmField public val MOSS_CARPET: ItemType = register("moss_carpet")
    @JvmField public val MOSS_BLOCK: ItemType = register("moss_block")
    @JvmField public val HANGING_ROOTS: ItemType = register("hanging_roots")
    @JvmField public val BIG_DRIPLEAF: ItemType = register("big_dripleaf")
    @JvmField public val SMALL_DRIPLEAF: ItemType = register("small_dripleaf")
    @JvmField public val BAMBOO: ItemType = register("bamboo")
    @JvmField public val OAK_SLAB: ItemType = register("oak_slab")
    @JvmField public val SPRUCE_SLAB: ItemType = register("spruce_slab")
    @JvmField public val BIRCH_SLAB: ItemType = register("birch_slab")
    @JvmField public val JUNGLE_SLAB: ItemType = register("jungle_slab")
    @JvmField public val ACACIA_SLAB: ItemType = register("acacia_slab")
    @JvmField public val DARK_OAK_SLAB: ItemType = register("dark_oak_slab")
    @JvmField public val CRIMSON_SLAB: ItemType = register("crimson_slab")
    @JvmField public val WARPED_SLAB: ItemType = register("warped_slab")
    @JvmField public val STONE_SLAB: ItemType = register("stone_slab")
    @JvmField public val SMOOTH_STONE_SLAB: ItemType = register("smooth_stone_slab")
    @JvmField public val SANDSTONE_SLAB: ItemType = register("sandstone_slab")
    @JvmField public val CUT_SANDSTONE_SLAB: ItemType = register("cut_sandstone_slab")
    @JvmField public val PETRIFIED_OAK_SLAB: ItemType = register("petrified_oak_slab")
    @JvmField public val COBBLESTONE_SLAB: ItemType = register("cobblestone_slab")
    @JvmField public val BRICK_SLAB: ItemType = register("brick_slab")
    @JvmField public val STONE_BRICK_SLAB: ItemType = register("stone_brick_slab")
    @JvmField public val NETHER_BRICK_SLAB: ItemType = register("nether_brick_slab")
    @JvmField public val QUARTZ_SLAB: ItemType = register("quartz_slab")
    @JvmField public val RED_SANDSTONE_SLAB: ItemType = register("red_sandstone_slab")
    @JvmField public val CUT_RED_SANDSTONE_SLAB: ItemType = register("cut_red_sandstone_slab")
    @JvmField public val PURPUR_SLAB: ItemType = register("purpur_slab")
    @JvmField public val PRISMARINE_SLAB: ItemType = register("prismarine_slab")
    @JvmField public val PRISMARINE_BRICK_SLAB: ItemType = register("prismarine_brick_slab")
    @JvmField public val DARK_PRISMARINE_SLAB: ItemType = register("dark_prismarine_slab")
    @JvmField public val SMOOTH_QUARTZ: ItemType = register("smooth_quartz")
    @JvmField public val SMOOTH_RED_SANDSTONE: ItemType = register("smooth_red_sandstone")
    @JvmField public val SMOOTH_SANDSTONE: ItemType = register("smooth_sandstone")
    @JvmField public val SMOOTH_STONE: ItemType = register("smooth_stone")
    @JvmField public val BRICKS: ItemType = register("bricks")
    @JvmField public val BOOKSHELF: ItemType = register("bookshelf")
    @JvmField public val MOSSY_COBBLESTONE: ItemType = register("mossy_cobblestone")
    @JvmField public val OBSIDIAN: ItemType = register("obsidian")
    @JvmField public val TORCH: ItemType = register("torch")
    @JvmField public val END_ROD: ItemType = register("end_rod")
    @JvmField public val CHORUS_PLANT: ItemType = register("chorus_plant")
    @JvmField public val CHORUS_FLOWER: ItemType = register("chorus_flower")
    @JvmField public val PURPUR_BLOCK: ItemType = register("purpur_block")
    @JvmField public val PURPUR_PILLAR: ItemType = register("purpur_pillar")
    @JvmField public val PURPUR_STAIRS: ItemType = register("purpur_stairs")
    @JvmField public val SPAWNER: ItemType = register("spawner", ItemRarity.EPIC)
    @JvmField public val OAK_STAIRS: ItemType = register("oak_stairs")
    @JvmField public val CHEST: ItemType = register("chest")
    @JvmField public val CRAFTING_TABLE: ItemType = register("crafting_table")
    @JvmField public val FARMLAND: ItemType = register("farmland")
    @JvmField public val FURNACE: ItemType = register("furnace")
    @JvmField public val LADDER: ItemType = register("ladder")
    @JvmField public val COBBLESTONE_STAIRS: ItemType = register("cobblestone_stairs")
    @JvmField public val SNOW: ItemType = register("snow")
    @JvmField public val ICE: ItemType = register("ice")
    @JvmField public val SNOW_BLOCK: ItemType = register("snow_block")
    @JvmField public val CACTUS: ItemType = register("cactus")
    @JvmField public val CLAY: ItemType = register("clay")
    @JvmField public val JUKEBOX: ItemType = register("jukebox")
    @JvmField public val OAK_FENCE: ItemType = register("oak_fence")
    @JvmField public val SPRUCE_FENCE: ItemType = register("spruce_fence")
    @JvmField public val BIRCH_FENCE: ItemType = register("birch_fence")
    @JvmField public val JUNGLE_FENCE: ItemType = register("jungle_fence")
    @JvmField public val ACACIA_FENCE: ItemType = register("acacia_fence")
    @JvmField public val DARK_OAK_FENCE: ItemType = register("dark_oak_fence")
    @JvmField public val CRIMSON_FENCE: ItemType = register("crimson_fence")
    @JvmField public val WARPED_FENCE: ItemType = register("warped_fence")
    @JvmField public val PUMPKIN: ItemType = register("pumpkin")
    @JvmField public val CARVED_PUMPKIN: ItemType = register("carved_pumpkin")
    @JvmField public val JACK_O_LANTERN: ItemType = register("jack_o_lantern")
    @JvmField public val NETHERRACK: ItemType = register("netherrack")
    @JvmField public val SOUL_SAND: ItemType = register("soul_sand")
    @JvmField public val SOUL_SOIL: ItemType = register("soul_soil")
    @JvmField public val BASALT: ItemType = register("basalt")
    @JvmField public val POLISHED_BASALT: ItemType = register("polished_basalt")
    @JvmField public val SMOOTH_BASALT: ItemType = register("smooth_basalt")
    @JvmField public val SOUL_TORCH: ItemType = register("soul_torch")
    @JvmField public val GLOWSTONE: ItemType = register("glowstone")
    @JvmField public val INFESTED_STONE: ItemType = register("infested_stone")
    @JvmField public val INFESTED_COBBLESTONE: ItemType = register("infested_cobblestone")
    @JvmField public val INFESTED_STONE_BRICKS: ItemType = register("infested_stone_bricks")
    @JvmField public val INFESTED_MOSSY_STONE_BRICKS: ItemType = register("infested_mossy_stone_bricks")
    @JvmField public val INFESTED_CRACKED_STONE_BRICKS: ItemType = register("infested_cracked_stone_bricks")
    @JvmField public val INFESTED_CHISELED_STONE_BRICKS: ItemType = register("infested_chiseled_stone_bricks")
    @JvmField public val INFESTED_DEEPSLATE: ItemType = register("infested_deepslate")
    @JvmField public val STONE_BRICKS: ItemType = register("stone_bricks")
    @JvmField public val MOSSY_STONE_BRICKS: ItemType = register("mossy_stone_bricks")
    @JvmField public val CRACKED_STONE_BRICKS: ItemType = register("cracked_stone_bricks")
    @JvmField public val CHISELED_STONE_BRICKS: ItemType = register("chiseled_stone_bricks")
    @JvmField public val DEEPSLATE_BRICKS: ItemType = register("deepslate_bricks")
    @JvmField public val CRACKED_DEEPSLATE_BRICKS: ItemType = register("cracked_deepslate_bricks")
    @JvmField public val DEEPSLATE_TILES: ItemType = register("deepslate_tiles")
    @JvmField public val CRACKED_DEEPSLATE_TILES: ItemType = register("cracked_deepslate_tiles")
    @JvmField public val CHISELED_DEEPSLATE: ItemType = register("chiseled_deepslate")
    @JvmField public val BROWN_MUSHROOM_BLOCK: ItemType = register("brown_mushroom_block")
    @JvmField public val RED_MUSHROOM_BLOCK: ItemType = register("red_mushroom_block")
    @JvmField public val MUSHROOM_STEM: ItemType = register("mushroom_stem")
    @JvmField public val IRON_BARS: ItemType = register("iron_bars")
    @JvmField public val CHAIN: ItemType = register("chain")
    @JvmField public val GLASS_PANE: ItemType = register("glass_pane")
    @JvmField public val MELON: ItemType = register("melon")
    @JvmField public val VINE: ItemType = register("vine")
    @JvmField public val GLOW_LICHEN: ItemType = register("glow_lichen")
    @JvmField public val BRICK_STAIRS: ItemType = register("brick_stairs")
    @JvmField public val STONE_BRICK_STAIRS: ItemType = register("stone_brick_stairs")
    @JvmField public val MYCELIUM: ItemType = register("mycelium")
    @JvmField public val LILY_PAD: ItemType = register("lily_pad")
    @JvmField public val NETHER_BRICKS: ItemType = register("nether_bricks")
    @JvmField public val CRACKED_NETHER_BRICKS: ItemType = register("cracked_nether_bricks")
    @JvmField public val CHISELED_NETHER_BRICKS: ItemType = register("chiseled_nether_bricks")
    @JvmField public val NETHER_BRICK_FENCE: ItemType = register("nether_brick_fence")
    @JvmField public val NETHER_BRICK_STAIRS: ItemType = register("nether_brick_stairs")
    @JvmField public val ENCHANTING_TABLE: ItemType = register("enchanting_table")
    @JvmField public val END_PORTAL_FRAME: ItemType = register("end_portal_frame")
    @JvmField public val END_STONE: ItemType = register("end_stone")
    @JvmField public val END_STONE_BRICKS: ItemType = register("end_stone_bricks")
    @JvmField public val DRAGON_EGG: ItemType = register("dragon_egg", ItemRarity.EPIC)
    @JvmField public val SANDSTONE_STAIRS: ItemType = register("sandstone_stairs")
    @JvmField public val ENDER_CHEST: ItemType = register("ender_chest")
    @JvmField public val EMERALD_BLOCK: ItemType = register("emerald_block")
    @JvmField public val SPRUCE_STAIRS: ItemType = register("spruce_stairs")
    @JvmField public val BIRCH_STAIRS: ItemType = register("birch_stairs")
    @JvmField public val JUNGLE_STAIRS: ItemType = register("jungle_stairs")
    @JvmField public val CRIMSON_STAIRS: ItemType = register("crimson_stairs")
    @JvmField public val WARPED_STAIRS: ItemType = register("warped_stairs")
    @JvmField public val COMMAND_BLOCK: ItemType = register("command_block", ItemRarity.EPIC)
    @JvmField public val BEACON: ItemType = register("beacon", ItemRarity.RARE)
    @JvmField public val COBBLESTONE_WALL: ItemType = register("cobblestone_wall")
    @JvmField public val MOSSY_COBBLESTONE_WALL: ItemType = register("mossy_cobblestone_wall")
    @JvmField public val BRICK_WALL: ItemType = register("brick_wall")
    @JvmField public val PRISMARINE_WALL: ItemType = register("prismarine_wall")
    @JvmField public val RED_SANDSTONE_WALL: ItemType = register("red_sandstone_wall")
    @JvmField public val MOSSY_STONE_BRICK_WALL: ItemType = register("mossy_stone_brick_wall")
    @JvmField public val GRANITE_WALL: ItemType = register("granite_wall")
    @JvmField public val STONE_BRICK_WALL: ItemType = register("stone_brick_wall")
    @JvmField public val NETHER_BRICK_WALL: ItemType = register("nether_brick_wall")
    @JvmField public val ANDESITE_WALL: ItemType = register("andesite_wall")
    @JvmField public val RED_NETHER_BRICK_WALL: ItemType = register("red_nether_brick_wall")
    @JvmField public val SANDSTONE_WALL: ItemType = register("sandstone_wall")
    @JvmField public val END_STONE_BRICK_WALL: ItemType = register("end_stone_brick_wall")
    @JvmField public val DIORITE_WALL: ItemType = register("diorite_wall")
    @JvmField public val BLACKSTONE_WALL: ItemType = register("blackstone_wall")
    @JvmField public val POLISHED_BLACKSTONE_WALL: ItemType = register("polished_blackstone_wall")
    @JvmField public val POLISHED_BLACKSTONE_BRICK_WALL: ItemType = register("polished_blackstone_brick_wall")
    @JvmField public val COBBLED_DEEPSLATE_WALL: ItemType = register("cobbled_deepslate_wall")
    @JvmField public val POLISHED_DEEPSLATE_WALL: ItemType = register("polished_deepslate_wall")
    @JvmField public val DEEPSLATE_BRICK_WALL: ItemType = register("deepslate_brick_wall")
    @JvmField public val DEEPSLATE_TILE_WALL: ItemType = register("deepslate_tile_wall")
    @JvmField public val ANVIL: ItemType = register("anvil")
    @JvmField public val CHIPPED_ANVIL: ItemType = register("chipped_anvil")
    @JvmField public val DAMAGED_ANVIL: ItemType = register("damaged_anvil")
    @JvmField public val CHISELED_QUARTZ_BLOCK: ItemType = register("chiseled_quartz_block")
    @JvmField public val QUARTZ_BLOCK: ItemType = register("quartz_block")
    @JvmField public val QUARTZ_BRICKS: ItemType = register("quartz_bricks")
    @JvmField public val QUARTZ_PILLAR: ItemType = register("quartz_pillar")
    @JvmField public val QUARTZ_STAIRS: ItemType = register("quartz_stairs")
    @JvmField public val WHITE_TERRACOTTA: ItemType = register("white_terracotta")
    @JvmField public val ORANGE_TERRACOTTA: ItemType = register("orange_terracotta")
    @JvmField public val MAGENTA_TERRACOTTA: ItemType = register("magenta_terracotta")
    @JvmField public val LIGHT_BLUE_TERRACOTTA: ItemType = register("light_blue_terracotta")
    @JvmField public val YELLOW_TERRACOTTA: ItemType = register("yellow_terracotta")
    @JvmField public val LIME_TERRACOTTA: ItemType = register("lime_terracotta")
    @JvmField public val PINK_TERRACOTTA: ItemType = register("pink_terracotta")
    @JvmField public val GRAY_TERRACOTTA: ItemType = register("gray_terracotta")
    @JvmField public val LIGHT_GRAY_TERRACOTTA: ItemType = register("light_gray_terracotta")
    @JvmField public val CYAN_TERRACOTTA: ItemType = register("cyan_terracotta")
    @JvmField public val PURPLE_TERRACOTTA: ItemType = register("purple_terracotta")
    @JvmField public val BLUE_TERRACOTTA: ItemType = register("blue_terracotta")
    @JvmField public val BROWN_TERRACOTTA: ItemType = register("brown_terracotta")
    @JvmField public val GREEN_TERRACOTTA: ItemType = register("green_terracotta")
    @JvmField public val RED_TERRACOTTA: ItemType = register("red_terracotta")
    @JvmField public val BLACK_TERRACOTTA: ItemType = register("black_terracotta")
    @JvmField public val BARRIER: ItemType = register("barrier", ItemRarity.EPIC)
    @JvmField public val LIGHT: ItemType = register("light", ItemRarity.EPIC)
    @JvmField public val HAY_BLOCK: ItemType = register("hay_block")
    @JvmField public val WHITE_CARPET: ItemType = register("white_carpet")
    @JvmField public val ORANGE_CARPET: ItemType = register("orange_carpet")
    @JvmField public val MAGENTA_CARPET: ItemType = register("magenta_carpet")
    @JvmField public val LIGHT_BLUE_CARPET: ItemType = register("light_blue_carpet")
    @JvmField public val YELLOW_CARPET: ItemType = register("yellow_carpet")
    @JvmField public val LIME_CARPET: ItemType = register("lime_carpet")
    @JvmField public val PINK_CARPET: ItemType = register("pink_carpet")
    @JvmField public val GRAY_CARPET: ItemType = register("gray_carpet")
    @JvmField public val LIGHT_GRAY_CARPET: ItemType = register("light_gray_carpet")
    @JvmField public val CYAN_CARPET: ItemType = register("cyan_carpet")
    @JvmField public val PURPLE_CARPET: ItemType = register("purple_carpet")
    @JvmField public val BLUE_CARPET: ItemType = register("blue_carpet")
    @JvmField public val BROWN_CARPET: ItemType = register("brown_carpet")
    @JvmField public val GREEN_CARPET: ItemType = register("green_carpet")
    @JvmField public val RED_CARPET: ItemType = register("red_carpet")
    @JvmField public val BLACK_CARPET: ItemType = register("black_carpet")
    @JvmField public val TERRACOTTA: ItemType = register("terracotta")
    @JvmField public val PACKED_ICE: ItemType = register("packed_ice")
    @JvmField public val ACACIA_STAIRS: ItemType = register("acacia_stairs")
    @JvmField public val DARK_OAK_STAIRS: ItemType = register("dark_oak_stairs")
    @JvmField public val DIRT_PATH: ItemType = register("dirt_path")
    @JvmField public val SUNFLOWER: ItemType = register("sunflower")
    @JvmField public val LILAC: ItemType = register("lilac")
    @JvmField public val ROSE_BUSH: ItemType = register("rose_bush")
    @JvmField public val PEONY: ItemType = register("peony")
    @JvmField public val TALL_GRASS: ItemType = register("tall_grass")
    @JvmField public val LARGE_FERN: ItemType = register("large_fern")
    @JvmField public val WHITE_STAINED_GLASS: ItemType = register("white_stained_glass")
    @JvmField public val ORANGE_STAINED_GLASS: ItemType = register("orange_stained_glass")
    @JvmField public val MAGENTA_STAINED_GLASS: ItemType = register("magenta_stained_glass")
    @JvmField public val LIGHT_BLUE_STAINED_GLASS: ItemType = register("light_blue_stained_glass")
    @JvmField public val YELLOW_STAINED_GLASS: ItemType = register("yellow_stained_glass")
    @JvmField public val LIME_STAINED_GLASS: ItemType = register("lime_stained_glass")
    @JvmField public val PINK_STAINED_GLASS: ItemType = register("pink_stained_glass")
    @JvmField public val GRAY_STAINED_GLASS: ItemType = register("gray_stained_glass")
    @JvmField public val LIGHT_GRAY_STAINED_GLASS: ItemType = register("light_gray_stained_glass")
    @JvmField public val CYAN_STAINED_GLASS: ItemType = register("cyan_stained_glass")
    @JvmField public val PURPLE_STAINED_GLASS: ItemType = register("purple_stained_glass")
    @JvmField public val BLUE_STAINED_GLASS: ItemType = register("blue_stained_glass")
    @JvmField public val BROWN_STAINED_GLASS: ItemType = register("brown_stained_glass")
    @JvmField public val GREEN_STAINED_GLASS: ItemType = register("green_stained_glass")
    @JvmField public val RED_STAINED_GLASS: ItemType = register("red_stained_glass")
    @JvmField public val BLACK_STAINED_GLASS: ItemType = register("black_stained_glass")
    @JvmField public val WHITE_STAINED_GLASS_PANE: ItemType = register("white_stained_glass_pane")
    @JvmField public val ORANGE_STAINED_GLASS_PANE: ItemType = register("orange_stained_glass_pane")
    @JvmField public val MAGENTA_STAINED_GLASS_PANE: ItemType = register("magenta_stained_glass_pane")
    @JvmField public val LIGHT_BLUE_STAINED_GLASS_PANE: ItemType = register("light_blue_stained_glass_pane")
    @JvmField public val YELLOW_STAINED_GLASS_PANE: ItemType = register("yellow_stained_glass_pane")
    @JvmField public val LIME_STAINED_GLASS_PANE: ItemType = register("lime_stained_glass_pane")
    @JvmField public val PINK_STAINED_GLASS_PANE: ItemType = register("pink_stained_glass_pane")
    @JvmField public val GRAY_STAINED_GLASS_PANE: ItemType = register("gray_stained_glass_pane")
    @JvmField public val LIGHT_GRAY_STAINED_GLASS_PANE: ItemType = register("light_gray_stained_glass_pane")
    @JvmField public val CYAN_STAINED_GLASS_PANE: ItemType = register("cyan_stained_glass_pane")
    @JvmField public val PURPLE_STAINED_GLASS_PANE: ItemType = register("purple_stained_glass_pane")
    @JvmField public val BLUE_STAINED_GLASS_PANE: ItemType = register("blue_stained_glass_pane")
    @JvmField public val BROWN_STAINED_GLASS_PANE: ItemType = register("brown_stained_glass_pane")
    @JvmField public val GREEN_STAINED_GLASS_PANE: ItemType = register("green_stained_glass_pane")
    @JvmField public val RED_STAINED_GLASS_PANE: ItemType = register("red_stained_glass_pane")
    @JvmField public val BLACK_STAINED_GLASS_PANE: ItemType = register("black_stained_glass_pane")
    @JvmField public val PRISMARINE: ItemType = register("prismarine")
    @JvmField public val PRISMARINE_BRICKS: ItemType = register("prismarine_bricks")
    @JvmField public val DARK_PRISMARINE: ItemType = register("dark_prismarine")
    @JvmField public val PRISMARINE_STAIRS: ItemType = register("prismarine_stairs")
    @JvmField public val PRISMARINE_BRICK_STAIRS: ItemType = register("prismarine_brick_stairs")
    @JvmField public val DARK_PRISMARINE_STAIRS: ItemType = register("dark_prismarine_stairs")
    @JvmField public val SEA_LANTERN: ItemType = register("sea_lantern")
    @JvmField public val RED_SANDSTONE: ItemType = register("red_sandstone")
    @JvmField public val CHISELED_RED_SANDSTONE: ItemType = register("chiseled_red_sandstone")
    @JvmField public val CUT_RED_SANDSTONE: ItemType = register("cut_red_sandstone")
    @JvmField public val RED_SANDSTONE_STAIRS: ItemType = register("red_sandstone_stairs")
    @JvmField public val REPEATING_COMMAND_BLOCK: ItemType = register("repeating_command_block", ItemRarity.EPIC)
    @JvmField public val CHAIN_COMMAND_BLOCK: ItemType = register("chain_command_block", ItemRarity.EPIC)
    @JvmField public val MAGMA_BLOCK: ItemType = register("magma_block")
    @JvmField public val NETHER_WART_BLOCK: ItemType = register("nether_wart_block")
    @JvmField public val WARPED_WART_BLOCK: ItemType = register("warped_wart_block")
    @JvmField public val RED_NETHER_BRICKS: ItemType = register("red_nether_bricks")
    @JvmField public val BONE_BLOCK: ItemType = register("bone_block")
    @JvmField public val STRUCTURE_VOID: ItemType = register("structure_void", ItemRarity.EPIC)
    @JvmField public val SHULKER_BOX: ItemType = register("shulker_box", maximumAmount = 1)
    @JvmField public val WHITE_SHULKER_BOX: ItemType = register("white_shulker_box", maximumAmount = 1)
    @JvmField public val ORANGE_SHULKER_BOX: ItemType = register("orange_shulker_box", maximumAmount = 1)
    @JvmField public val MAGENTA_SHULKER_BOX: ItemType = register("magenta_shulker_box", maximumAmount = 1)
    @JvmField public val LIGHT_BLUE_SHULKER_BOX: ItemType = register("light_blue_shulker_box", maximumAmount = 1)
    @JvmField public val YELLOW_SHULKER_BOX: ItemType = register("yellow_shulker_box", maximumAmount = 1)
    @JvmField public val LIME_SHULKER_BOX: ItemType = register("lime_shulker_box", maximumAmount = 1)
    @JvmField public val PINK_SHULKER_BOX: ItemType = register("pink_shulker_box", maximumAmount = 1)
    @JvmField public val GRAY_SHULKER_BOX: ItemType = register("gray_shulker_box", maximumAmount = 1)
    @JvmField public val LIGHT_GRAY_SHULKER_BOX: ItemType = register("light_gray_shulker_box", maximumAmount = 1)
    @JvmField public val CYAN_SHULKER_BOX: ItemType = register("cyan_shulker_box", maximumAmount = 1)
    @JvmField public val PURPLE_SHULKER_BOX: ItemType = register("purple_shulker_box", maximumAmount = 1)
    @JvmField public val BLUE_SHULKER_BOX: ItemType = register("blue_shulker_box", maximumAmount = 1)
    @JvmField public val BROWN_SHULKER_BOX: ItemType = register("brown_shulker_box", maximumAmount = 1)
    @JvmField public val GREEN_SHULKER_BOX: ItemType = register("green_shulker_box", maximumAmount = 1)
    @JvmField public val RED_SHULKER_BOX: ItemType = register("red_shulker_box", maximumAmount = 1)
    @JvmField public val BLACK_SHULKER_BOX: ItemType = register("black_shulker_box", maximumAmount = 1)
    @JvmField public val WHITE_GLAZED_TERRACOTTA: ItemType = register("white_glazed_terracotta")
    @JvmField public val ORANGE_GLAZED_TERRACOTTA: ItemType = register("orange_glazed_terracotta")
    @JvmField public val MAGENTA_GLAZED_TERRACOTTA: ItemType = register("magenta_glazed_terracotta")
    @JvmField public val LIGHT_BLUE_GLAZED_TERRACOTTA: ItemType = register("light_blue_glazed_terracotta")
    @JvmField public val YELLOW_GLAZED_TERRACOTTA: ItemType = register("yellow_glazed_terracotta")
    @JvmField public val LIME_GLAZED_TERRACOTTA: ItemType = register("lime_glazed_terracotta")
    @JvmField public val PINK_GLAZED_TERRACOTTA: ItemType = register("pink_glazed_terracotta")
    @JvmField public val GRAY_GLAZED_TERRACOTTA: ItemType = register("gray_glazed_terracotta")
    @JvmField public val LIGHT_GRAY_GLAZED_TERRACOTTA: ItemType = register("light_gray_glazed_terracotta")
    @JvmField public val CYAN_GLAZED_TERRACOTTA: ItemType = register("cyan_glazed_terracotta")
    @JvmField public val PURPLE_GLAZED_TERRACOTTA: ItemType = register("purple_glazed_terracotta")
    @JvmField public val BLUE_GLAZED_TERRACOTTA: ItemType = register("blue_glazed_terracotta")
    @JvmField public val BROWN_GLAZED_TERRACOTTA: ItemType = register("brown_glazed_terracotta")
    @JvmField public val GREEN_GLAZED_TERRACOTTA: ItemType = register("green_glazed_terracotta")
    @JvmField public val RED_GLAZED_TERRACOTTA: ItemType = register("red_glazed_terracotta")
    @JvmField public val BLACK_GLAZED_TERRACOTTA: ItemType = register("black_glazed_terracotta")
    @JvmField public val WHITE_CONCRETE: ItemType = register("white_concrete")
    @JvmField public val ORANGE_CONCRETE: ItemType = register("orange_concrete")
    @JvmField public val MAGENTA_CONCRETE: ItemType = register("magenta_concrete")
    @JvmField public val LIGHT_BLUE_CONCRETE: ItemType = register("light_blue_concrete")
    @JvmField public val YELLOW_CONCRETE: ItemType = register("yellow_concrete")
    @JvmField public val LIME_CONCRETE: ItemType = register("lime_concrete")
    @JvmField public val PINK_CONCRETE: ItemType = register("pink_concrete")
    @JvmField public val GRAY_CONCRETE: ItemType = register("gray_concrete")
    @JvmField public val LIGHT_GRAY_CONCRETE: ItemType = register("light_gray_concrete")
    @JvmField public val CYAN_CONCRETE: ItemType = register("cyan_concrete")
    @JvmField public val PURPLE_CONCRETE: ItemType = register("purple_concrete")
    @JvmField public val BLUE_CONCRETE: ItemType = register("blue_concrete")
    @JvmField public val BROWN_CONCRETE: ItemType = register("brown_concrete")
    @JvmField public val GREEN_CONCRETE: ItemType = register("green_concrete")
    @JvmField public val RED_CONCRETE: ItemType = register("red_concrete")
    @JvmField public val BLACK_CONCRETE: ItemType = register("black_concrete")
    @JvmField public val WHITE_CONCRETE_POWDER: ItemType = register("white_concrete_powder")
    @JvmField public val ORANGE_CONCRETE_POWDER: ItemType = register("orange_concrete_powder")
    @JvmField public val MAGENTA_CONCRETE_POWDER: ItemType = register("magenta_concrete_powder")
    @JvmField public val LIGHT_BLUE_CONCRETE_POWDER: ItemType = register("light_blue_concrete_powder")
    @JvmField public val YELLOW_CONCRETE_POWDER: ItemType = register("yellow_concrete_powder")
    @JvmField public val LIME_CONCRETE_POWDER: ItemType = register("lime_concrete_powder")
    @JvmField public val PINK_CONCRETE_POWDER: ItemType = register("pink_concrete_powder")
    @JvmField public val GRAY_CONCRETE_POWDER: ItemType = register("gray_concrete_powder")
    @JvmField public val LIGHT_GRAY_CONCRETE_POWDER: ItemType = register("light_gray_concrete_powder")
    @JvmField public val CYAN_CONCRETE_POWDER: ItemType = register("cyan_concrete_powder")
    @JvmField public val PURPLE_CONCRETE_POWDER: ItemType = register("purple_concrete_powder")
    @JvmField public val BLUE_CONCRETE_POWDER: ItemType = register("blue_concrete_powder")
    @JvmField public val BROWN_CONCRETE_POWDER: ItemType = register("brown_concrete_powder")
    @JvmField public val GREEN_CONCRETE_POWDER: ItemType = register("green_concrete_powder")
    @JvmField public val RED_CONCRETE_POWDER: ItemType = register("red_concrete_powder")
    @JvmField public val BLACK_CONCRETE_POWDER: ItemType = register("black_concrete_powder")
    @JvmField public val TURTLE_EGG: ItemType = register("turtle_egg")
    @JvmField public val DEAD_TUBE_CORAL_BLOCK: ItemType = register("dead_tube_coral_block")
    @JvmField public val DEAD_BRAIN_CORAL_BLOCK: ItemType = register("dead_brain_coral_block")
    @JvmField public val DEAD_BUBBLE_CORAL_BLOCK: ItemType = register("dead_bubble_coral_block")
    @JvmField public val DEAD_FIRE_CORAL_BLOCK: ItemType = register("dead_fire_coral_block")
    @JvmField public val DEAD_HORN_CORAL_BLOCK: ItemType = register("dead_horn_coral_block")
    @JvmField public val TUBE_CORAL_BLOCK: ItemType = register("tube_coral_block")
    @JvmField public val BRAIN_CORAL_BLOCK: ItemType = register("brain_coral_block")
    @JvmField public val BUBBLE_CORAL_BLOCK: ItemType = register("bubble_coral_block")
    @JvmField public val FIRE_CORAL_BLOCK: ItemType = register("fire_coral_block")
    @JvmField public val HORN_CORAL_BLOCK: ItemType = register("horn_coral_block")
    @JvmField public val TUBE_CORAL: ItemType = register("tube_coral")
    @JvmField public val BRAIN_CORAL: ItemType = register("brain_coral")
    @JvmField public val BUBBLE_CORAL: ItemType = register("bubble_coral")
    @JvmField public val FIRE_CORAL: ItemType = register("fire_coral")
    @JvmField public val HORN_CORAL: ItemType = register("horn_coral")
    @JvmField public val DEAD_BRAIN_CORAL: ItemType = register("dead_brain_coral")
    @JvmField public val DEAD_BUBBLE_CORAL: ItemType = register("dead_bubble_coral")
    @JvmField public val DEAD_FIRE_CORAL: ItemType = register("dead_fire_coral")
    @JvmField public val DEAD_HORN_CORAL: ItemType = register("dead_horn_coral")
    @JvmField public val DEAD_TUBE_CORAL: ItemType = register("dead_tube_coral")
    @JvmField public val TUBE_CORAL_FAN: ItemType = register("tube_coral_fan")
    @JvmField public val BRAIN_CORAL_FAN: ItemType = register("brain_coral_fan")
    @JvmField public val BUBBLE_CORAL_FAN: ItemType = register("bubble_coral_fan")
    @JvmField public val FIRE_CORAL_FAN: ItemType = register("fire_coral_fan")
    @JvmField public val HORN_CORAL_FAN: ItemType = register("horn_coral_fan")
    @JvmField public val DEAD_TUBE_CORAL_FAN: ItemType = register("dead_tube_coral_fan")
    @JvmField public val DEAD_BRAIN_CORAL_FAN: ItemType = register("dead_brain_coral_fan")
    @JvmField public val DEAD_BUBBLE_CORAL_FAN: ItemType = register("dead_bubble_coral_fan")
    @JvmField public val DEAD_FIRE_CORAL_FAN: ItemType = register("dead_fire_coral_fan")
    @JvmField public val DEAD_HORN_CORAL_FAN: ItemType = register("dead_horn_coral_fan")
    @JvmField public val BLUE_ICE: ItemType = register("blue_ice")
    @JvmField public val CONDUIT: ItemType = register("conduit", ItemRarity.RARE)
    @JvmField public val POLISHED_GRANITE_STAIRS: ItemType = register("polished_granite_stairs")
    @JvmField public val SMOOTH_RED_SANDSTONE_STAIRS: ItemType = register("smooth_red_sandstone_stairs")
    @JvmField public val MOSSY_STONE_BRICK_STAIRS: ItemType = register("mossy_stone_brick_stairs")
    @JvmField public val POLISHED_DIORITE_STAIRS: ItemType = register("polished_diorite_stairs")
    @JvmField public val MOSSY_COBBLESTONE_STAIRS: ItemType = register("mossy_cobblestone_stairs")
    @JvmField public val END_STONE_BRICK_STAIRS: ItemType = register("end_stone_brick_stairs")
    @JvmField public val STONE_STAIRS: ItemType = register("stone_stairs")
    @JvmField public val SMOOTH_SANDSTONE_STAIRS: ItemType = register("smooth_sandstone_stairs")
    @JvmField public val SMOOTH_QUARTZ_STAIRS: ItemType = register("smooth_quartz_stairs")
    @JvmField public val GRANITE_STAIRS: ItemType = register("granite_stairs")
    @JvmField public val ANDESITE_STAIRS: ItemType = register("andesite_stairs")
    @JvmField public val RED_NETHER_BRICK_STAIRS: ItemType = register("red_nether_brick_stairs")
    @JvmField public val POLISHED_ANDESITE_STAIRS: ItemType = register("polished_andesite_stairs")
    @JvmField public val DIORITE_STAIRS: ItemType = register("diorite_stairs")
    @JvmField public val COBBLED_DEEPSLATE_STAIRS: ItemType = register("cobbled_deepslate_stairs")
    @JvmField public val POLISHED_DEEPSLATE_STAIRS: ItemType = register("polished_deepslate_stairs")
    @JvmField public val DEEPSLATE_BRICK_STAIRS: ItemType = register("deepslate_brick_stairs")
    @JvmField public val DEEPSLATE_TILE_STAIRS: ItemType = register("deepslate_tile_stairs")
    @JvmField public val POLISHED_GRANITE_SLAB: ItemType = register("polished_granite_slab")
    @JvmField public val SMOOTH_RED_SANDSTONE_SLAB: ItemType = register("smooth_red_sandstone_slab")
    @JvmField public val MOSSY_STONE_BRICK_SLAB: ItemType = register("mossy_stone_brick_slab")
    @JvmField public val POLISHED_DIORITE_SLAB: ItemType = register("polished_diorite_slab")
    @JvmField public val MOSSY_COBBLESTONE_SLAB: ItemType = register("mossy_cobblestone_slab")
    @JvmField public val END_STONE_BRICK_SLAB: ItemType = register("end_stone_brick_slab")
    @JvmField public val SMOOTH_SANDSTONE_SLAB: ItemType = register("smooth_sandstone_slab")
    @JvmField public val SMOOTH_QUARTZ_SLAB: ItemType = register("smooth_quartz_slab")
    @JvmField public val GRANITE_SLAB: ItemType = register("granite_slab")
    @JvmField public val ANDESITE_SLAB: ItemType = register("andesite_slab")
    @JvmField public val RED_NETHER_BRICK_SLAB: ItemType = register("red_nether_brick_slab")
    @JvmField public val POLISHED_ANDESITE_SLAB: ItemType = register("polished_andesite_slab")
    @JvmField public val DIORITE_SLAB: ItemType = register("diorite_slab")
    @JvmField public val COBBLED_DEEPSLATE_SLAB: ItemType = register("cobbled_deepslate_slab")
    @JvmField public val POLISHED_DEEPSLATE_SLAB: ItemType = register("polished_deepslate_slab")
    @JvmField public val DEEPSLATE_BRICK_SLAB: ItemType = register("deepslate_brick_slab")
    @JvmField public val DEEPSLATE_TILE_SLAB: ItemType = register("deepslate_tile_slab")
    @JvmField public val SCAFFOLDING: ItemType = register("scaffolding")
    @JvmField public val REDSTONE: ItemType = register("redstone")
    @JvmField public val REDSTONE_TORCH: ItemType = register("redstone_torch")
    @JvmField public val REDSTONE_BLOCK: ItemType = register("redstone_block")
    @JvmField public val REPEATER: ItemType = register("repeater")
    @JvmField public val COMPARATOR: ItemType = register("comparator")
    @JvmField public val PISTON: ItemType = register("piston")
    @JvmField public val STICKY_PISTON: ItemType = register("sticky_piston")
    @JvmField public val SLIME_BLOCK: ItemType = register("slime_block")
    @JvmField public val HONEY_BLOCK: ItemType = register("honey_block")
    @JvmField public val OBSERVER: ItemType = register("observer")
    @JvmField public val HOPPER: ItemType = register("hopper")
    @JvmField public val DISPENSER: ItemType = register("dispenser")
    @JvmField public val DROPPER: ItemType = register("dropper")
    @JvmField public val LECTERN: ItemType = register("lectern")
    @JvmField public val TARGET: ItemType = register("target")
    @JvmField public val LEVER: ItemType = register("lever")
    @JvmField public val LIGHTNING_ROD: ItemType = register("lightning_rod")
    @JvmField public val DAYLIGHT_DETECTOR: ItemType = register("daylight_detector")
    @JvmField public val SCULK_SENSOR: ItemType = register("sculk_sensor")
    @JvmField public val TRIPWIRE_HOOK: ItemType = register("tripwire_hook")
    @JvmField public val TRAPPED_CHEST: ItemType = register("trapped_chest")
    @JvmField public val TNT: ItemType = register("tnt")
    @JvmField public val REDSTONE_LAMP: ItemType = register("redstone_lamp")
    @JvmField public val NOTE_BLOCK: ItemType = register("note_block")
    @JvmField public val STONE_BUTTON: ItemType = register("stone_button")
    @JvmField public val POLISHED_BLACKSTONE_BUTTON: ItemType = register("polished_blackstone_button")
    @JvmField public val OAK_BUTTON: ItemType = register("oak_button")
    @JvmField public val SPRUCE_BUTTON: ItemType = register("spruce_button")
    @JvmField public val BIRCH_BUTTON: ItemType = register("birch_button")
    @JvmField public val JUNGLE_BUTTON: ItemType = register("jungle_button")
    @JvmField public val ACACIA_BUTTON: ItemType = register("acacia_button")
    @JvmField public val DARK_OAK_BUTTON: ItemType = register("dark_oak_button")
    @JvmField public val CRIMSON_BUTTON: ItemType = register("crimson_button")
    @JvmField public val WARPED_BUTTON: ItemType = register("warped_button")
    @JvmField public val STONE_PRESSURE_PLATE: ItemType = register("stone_pressure_plate")
    @JvmField public val POLISHED_BLACKSTONE_PRESSURE_PLATE: ItemType =
        register("polished_blackstone_pressure_plate")
    @JvmField public val LIGHT_WEIGHTED_PRESSURE_PLATE: ItemType = register("light_weighted_pressure_plate")
    @JvmField public val HEAVY_WEIGHTED_PRESSURE_PLATE: ItemType = register("heavy_weighted_pressure_plate")
    @JvmField public val OAK_PRESSURE_PLATE: ItemType = register("oak_pressure_plate")
    @JvmField public val SPRUCE_PRESSURE_PLATE: ItemType = register("spruce_pressure_plate")
    @JvmField public val BIRCH_PRESSURE_PLATE: ItemType = register("birch_pressure_plate")
    @JvmField public val JUNGLE_PRESSURE_PLATE: ItemType = register("jungle_pressure_plate")
    @JvmField public val ACACIA_PRESSURE_PLATE: ItemType = register("acacia_pressure_plate")
    @JvmField public val DARK_OAK_PRESSURE_PLATE: ItemType = register("dark_oak_pressure_plate")
    @JvmField public val CRIMSON_PRESSURE_PLATE: ItemType = register("crimson_pressure_plate")
    @JvmField public val WARPED_PRESSURE_PLATE: ItemType = register("warped_pressure_plate")
    @JvmField public val IRON_DOOR: ItemType = register("iron_door")
    @JvmField public val OAK_DOOR: ItemType = register("oak_door")
    @JvmField public val SPRUCE_DOOR: ItemType = register("spruce_door")
    @JvmField public val BIRCH_DOOR: ItemType = register("birch_door")
    @JvmField public val JUNGLE_DOOR: ItemType = register("jungle_door")
    @JvmField public val ACACIA_DOOR: ItemType = register("acacia_door")
    @JvmField public val DARK_OAK_DOOR: ItemType = register("dark_oak_door")
    @JvmField public val CRIMSON_DOOR: ItemType = register("crimson_door")
    @JvmField public val WARPED_DOOR: ItemType = register("warped_door")
    @JvmField public val IRON_TRAPDOOR: ItemType = register("iron_trapdoor")
    @JvmField public val OAK_TRAPDOOR: ItemType = register("oak_trapdoor")
    @JvmField public val SPRUCE_TRAPDOOR: ItemType = register("spruce_trapdoor")
    @JvmField public val BIRCH_TRAPDOOR: ItemType = register("birch_trapdoor")
    @JvmField public val JUNGLE_TRAPDOOR: ItemType = register("jungle_trapdoor")
    @JvmField public val ACACIA_TRAPDOOR: ItemType = register("acacia_trapdoor")
    @JvmField public val DARK_OAK_TRAPDOOR: ItemType = register("dark_oak_trapdoor")
    @JvmField public val CRIMSON_TRAPDOOR: ItemType = register("crimson_trapdoor")
    @JvmField public val WARPED_TRAPDOOR: ItemType = register("warped_trapdoor")
    @JvmField public val OAK_FENCE_GATE: ItemType = register("oak_fence_gate")
    @JvmField public val SPRUCE_FENCE_GATE: ItemType = register("spruce_fence_gate")
    @JvmField public val BIRCH_FENCE_GATE: ItemType = register("birch_fence_gate")
    @JvmField public val JUNGLE_FENCE_GATE: ItemType = register("jungle_fence_gate")
    @JvmField public val ACACIA_FENCE_GATE: ItemType = register("acacia_fence_gate")
    @JvmField public val DARK_OAK_FENCE_GATE: ItemType = register("dark_oak_fence_gate")
    @JvmField public val CRIMSON_FENCE_GATE: ItemType = register("crimson_fence_gate")
    @JvmField public val WARPED_FENCE_GATE: ItemType = register("warped_fence_gate")
    @JvmField public val POWERED_RAIL: ItemType = register("powered_rail")
    @JvmField public val DETECTOR_RAIL: ItemType = register("detector_rail")
    @JvmField public val RAIL: ItemType = register("rail")
    @JvmField public val ACTIVATOR_RAIL: ItemType = register("activator_rail")
    @JvmField public val SADDLE: ItemType = register("saddle", maximumAmount = 1)
    @JvmField public val MINECART: ItemType = register("minecart", maximumAmount = 1)
    @JvmField public val CHEST_MINECART: ItemType = register("chest_minecart", maximumAmount = 1)
    @JvmField public val FURNACE_MINECART: ItemType = register("furnace_minecart", maximumAmount = 1)
    @JvmField public val TNT_MINECART: ItemType = register("tnt_minecart", maximumAmount = 1)
    @JvmField public val HOPPER_MINECART: ItemType = register("hopper_minecart", maximumAmount = 1)
    @JvmField public val CARROT_ON_A_STICK: ItemType =
        register("carrot_on_a_stick", maximumAmount = 1, durability = 25)
    @JvmField public val WARPED_FUNGUS_ON_A_STICK: ItemType =
        register("warped_fungus_on_a_stick", maximumAmount = 1, durability = 100)
    @JvmField public val ELYTRA: ItemType = register("elytra", maximumAmount = 1, durability = 432)
    @JvmField public val OAK_BOAT: ItemType = register("oak_boat", maximumAmount = 1)
    @JvmField public val SPRUCE_BOAT: ItemType = register("spruce_boat", maximumAmount = 1)
    @JvmField public val BIRCH_BOAT: ItemType = register("birch_boat", maximumAmount = 1)
    @JvmField public val JUNGLE_BOAT: ItemType = register("jungle_boat", maximumAmount = 1)
    @JvmField public val ACACIA_BOAT: ItemType = register("acacia_boat", maximumAmount = 1)
    @JvmField public val DARK_OAK_BOAT: ItemType = register("dark_oak_boat", maximumAmount = 1)
    @JvmField public val STRUCTURE_BLOCK: ItemType = register("structure_block", ItemRarity.EPIC)
    @JvmField public val JIGSAW: ItemType = register("jigsaw", ItemRarity.EPIC)
    @JvmField public val TURTLE_HELMET: ItemType = register("turtle_helmet", maximumAmount = 1)
    @JvmField public val SCUTE: ItemType = register("scute")
    @JvmField public val FLINT_AND_STEEL: ItemType =
        register("flint_and_steel", maximumAmount = 1, durability = 64)
    @JvmField public val APPLE: ItemType = register("apple")
    @JvmField public val BOW: ItemType = register("bow", maximumAmount = 1, durability = 384)
    @JvmField public val ARROW: ItemType = register("arrow")
    @JvmField public val COAL: ItemType = register("coal")
    @JvmField public val CHARCOAL: ItemType = register("charcoal")
    @JvmField public val DIAMOND: ItemType = register("diamond")
    @JvmField public val EMERALD: ItemType = register("emerald")
    @JvmField public val LAPIS_LAZULI: ItemType = register("lapis_lazuli")
    @JvmField public val QUARTZ: ItemType = register("quartz")
    @JvmField public val AMETHYST_SHARD: ItemType = register("amethyst_shard")
    @JvmField public val RAW_IRON: ItemType = register("raw_iron")
    @JvmField public val IRON_INGOT: ItemType = register("iron_ingot")
    @JvmField public val RAW_COPPER: ItemType = register("raw_copper")
    @JvmField public val COPPER_INGOT: ItemType = register("copper_ingot")
    @JvmField public val RAW_GOLD: ItemType = register("raw_gold")
    @JvmField public val GOLD_INGOT: ItemType = register("gold_ingot")
    @JvmField public val NETHERITE_INGOT: ItemType = register("netherite_ingot", isFireResistant = true)
    @JvmField public val NETHERITE_SCRAP: ItemType = register("netherite_scrap", isFireResistant = true)
    @JvmField public val WOODEN_SWORD: ItemType = register("wooden_sword", maximumAmount = 1)
    @JvmField public val WOODEN_SHOVEL: ItemType = register("wooden_shovel", maximumAmount = 1)
    @JvmField public val WOODEN_PICKAXE: ItemType = register("wooden_pickaxe", maximumAmount = 1)
    @JvmField public val WOODEN_AXE: ItemType = register("wooden_axe", maximumAmount = 1)
    @JvmField public val WOODEN_HOE: ItemType = register("wooden_hoe", maximumAmount = 1)
    @JvmField public val STONE_SWORD: ItemType = register("stone_sword", maximumAmount = 1)
    @JvmField public val STONE_SHOVEL: ItemType = register("stone_shovel", maximumAmount = 1)
    @JvmField public val STONE_PICKAXE: ItemType = register("stone_pickaxe", maximumAmount = 1)
    @JvmField public val STONE_AXE: ItemType = register("stone_axe", maximumAmount = 1)
    @JvmField public val STONE_HOE: ItemType = register("stone_hoe", maximumAmount = 1)
    @JvmField public val GOLDEN_SWORD: ItemType = register("golden_sword", maximumAmount = 1)
    @JvmField public val GOLDEN_SHOVEL: ItemType = register("golden_shovel", maximumAmount = 1)
    @JvmField public val GOLDEN_PICKAXE: ItemType = register("golden_pickaxe", maximumAmount = 1)
    @JvmField public val GOLDEN_AXE: ItemType = register("golden_axe", maximumAmount = 1)
    @JvmField public val GOLDEN_HOE: ItemType = register("golden_hoe", maximumAmount = 1)
    @JvmField public val IRON_SWORD: ItemType = register("iron_sword", maximumAmount = 1)
    @JvmField public val IRON_SHOVEL: ItemType = register("iron_shovel", maximumAmount = 1)
    @JvmField public val IRON_PICKAXE: ItemType = register("iron_pickaxe", maximumAmount = 1)
    @JvmField public val IRON_AXE: ItemType = register("iron_axe", maximumAmount = 1)
    @JvmField public val IRON_HOE: ItemType = register("iron_hoe", maximumAmount = 1)
    @JvmField public val DIAMOND_SWORD: ItemType = register("diamond_sword", maximumAmount = 1)
    @JvmField public val DIAMOND_SHOVEL: ItemType = register("diamond_shovel", maximumAmount = 1)
    @JvmField public val DIAMOND_PICKAXE: ItemType = register("diamond_pickaxe", maximumAmount = 1)
    @JvmField public val DIAMOND_AXE: ItemType = register("diamond_axe", maximumAmount = 1)
    @JvmField public val DIAMOND_HOE: ItemType = register("diamond_hoe", maximumAmount = 1)
    @JvmField public val NETHERITE_SWORD: ItemType =
        register("netherite_sword", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_SHOVEL: ItemType =
        register("netherite_shovel", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_PICKAXE: ItemType =
        register("netherite_pickaxe", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_AXE: ItemType =
        register("netherite_axe", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_HOE: ItemType =
        register("netherite_hoe", maximumAmount = 1, isFireResistant = true)
    @JvmField public val STICK: ItemType = register("stick")
    @JvmField public val BOWL: ItemType = register("bowl")
    @JvmField public val MUSHROOM_STEW: ItemType = register("mushroom_stew", maximumAmount = 1)
    @JvmField public val STRING: ItemType = register("string")
    @JvmField public val FEATHER: ItemType = register("feather")
    @JvmField public val GUNPOWDER: ItemType = register("gunpowder")
    @JvmField public val WHEAT_SEEDS: ItemType = register("wheat_seeds")
    @JvmField public val WHEAT: ItemType = register("wheat")
    @JvmField public val BREAD: ItemType = register("bread")
    @JvmField public val LEATHER_HELMET: ItemType = register("leather_helmet", maximumAmount = 1)
    @JvmField public val LEATHER_CHESTPLATE: ItemType = register("leather_chestplate", maximumAmount = 1)
    @JvmField public val LEATHER_LEGGINGS: ItemType = register("leather_leggings", maximumAmount = 1)
    @JvmField public val LEATHER_BOOTS: ItemType = register("leather_boots", maximumAmount = 1)
    @JvmField public val CHAINMAIL_HELMET: ItemType = register("chainmail_helmet", maximumAmount = 1)
    @JvmField public val CHAINMAIL_CHESTPLATE: ItemType = register("chainmail_chestplate", maximumAmount = 1)
    @JvmField public val CHAINMAIL_LEGGINGS: ItemType = register("chainmail_leggings", maximumAmount = 1)
    @JvmField public val CHAINMAIL_BOOTS: ItemType = register("chainmail_boots", maximumAmount = 1)
    @JvmField public val IRON_HELMET: ItemType = register("iron_helmet", maximumAmount = 1)
    @JvmField public val IRON_CHESTPLATE: ItemType = register("iron_chestplate", maximumAmount = 1)
    @JvmField public val IRON_LEGGINGS: ItemType = register("iron_leggings", maximumAmount = 1)
    @JvmField public val IRON_BOOTS: ItemType = register("iron_boots", maximumAmount = 1)
    @JvmField public val DIAMOND_HELMET: ItemType = register("diamond_helmet", maximumAmount = 1)
    @JvmField public val DIAMOND_CHESTPLATE: ItemType = register("diamond_chestplate", maximumAmount = 1)
    @JvmField public val DIAMOND_LEGGINGS: ItemType = register("diamond_leggings", maximumAmount = 1)
    @JvmField public val DIAMOND_BOOTS: ItemType = register("diamond_boots", maximumAmount = 1)
    @JvmField public val GOLDEN_HELMET: ItemType = register("golden_helmet", maximumAmount = 1)
    @JvmField public val GOLDEN_CHESTPLATE: ItemType = register("golden_chestplate", maximumAmount = 1)
    @JvmField public val GOLDEN_LEGGINGS: ItemType = register("golden_leggings", maximumAmount = 1)
    @JvmField public val GOLDEN_BOOTS: ItemType = register("golden_boots", maximumAmount = 1)
    @JvmField public val NETHERITE_HELMET: ItemType =
        register("netherite_helmet", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_CHESTPLATE: ItemType =
        register("netherite_chestplate", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_LEGGINGS: ItemType =
        register("netherite_leggings", maximumAmount = 1, isFireResistant = true)
    @JvmField public val NETHERITE_BOOTS: ItemType =
        register("netherite_boots", maximumAmount = 1, isFireResistant = true)
    @JvmField public val FLINT: ItemType = register("flint")
    @JvmField public val PORKCHOP: ItemType = register("porkchop")
    @JvmField public val COOKED_PORKCHOP: ItemType = register("cooked_porkchop")
    @JvmField public val PAINTING: ItemType = register("painting")
    @JvmField public val GOLDEN_APPLE: ItemType = register("golden_apple", ItemRarity.RARE)
    @JvmField public val ENCHANTED_GOLDEN_APPLE: ItemType = register("enchanted_golden_apple", ItemRarity.EPIC)
    @JvmField public val OAK_SIGN: ItemType = register("oak_sign", maximumAmount = 16)
    @JvmField public val SPRUCE_SIGN: ItemType = register("spruce_sign", maximumAmount = 16)
    @JvmField public val BIRCH_SIGN: ItemType = register("birch_sign", maximumAmount = 16)
    @JvmField public val JUNGLE_SIGN: ItemType = register("jungle_sign", maximumAmount = 16)
    @JvmField public val ACACIA_SIGN: ItemType = register("acacia_sign", maximumAmount = 16)
    @JvmField public val DARK_OAK_SIGN: ItemType = register("dark_oak_sign", maximumAmount = 16)
    @JvmField public val CRIMSON_SIGN: ItemType = register("crimson_sign", maximumAmount = 16)
    @JvmField public val WARPED_SIGN: ItemType = register("warped_sign", maximumAmount = 16)
    @JvmField public val BUCKET: ItemType = register("bucket", maximumAmount = 16)
    @JvmField public val WATER_BUCKET: ItemType = register("water_bucket", maximumAmount = 1)
    @JvmField public val LAVA_BUCKET: ItemType = register("lava_bucket", maximumAmount = 1)
    @JvmField public val POWDER_SNOW_BUCKET: ItemType = register("powder_snow_bucket", maximumAmount = 1)
    @JvmField public val SNOWBALL: ItemType = register("snowball", maximumAmount = 16)
    @JvmField public val LEATHER: ItemType = register("leather")
    @JvmField public val MILK_BUCKET: ItemType = register("milk_bucket", maximumAmount = 1)
    @JvmField public val PUFFERFISH_BUCKET: ItemType = register("pufferfish_bucket", maximumAmount = 1)
    @JvmField public val SALMON_BUCKET: ItemType = register("salmon_bucket", maximumAmount = 1)
    @JvmField public val COD_BUCKET: ItemType = register("cod_bucket", maximumAmount = 1)
    @JvmField public val TROPICAL_FISH_BUCKET: ItemType = register("tropical_fish_bucket", maximumAmount = 1)
    @JvmField public val AXOLOTL_BUCKET: ItemType = register("axolotl_bucket", maximumAmount = 1)
    @JvmField public val BRICK: ItemType = register("brick")
    @JvmField public val CLAY_BALL: ItemType = register("clay_ball")
    @JvmField public val DRIED_KELP_BLOCK: ItemType = register("dried_kelp_block")
    @JvmField public val PAPER: ItemType = register("paper")
    @JvmField public val BOOK: ItemType = register("book")
    @JvmField public val SLIME_BALL: ItemType = register("slime_ball")
    @JvmField public val EGG: ItemType = register("egg", maximumAmount = 16)
    @JvmField public val COMPASS: ItemType = register("compass")
    @JvmField public val BUNDLE: ItemType = register("bundle", maximumAmount = 1)
    @JvmField public val FISHING_ROD: ItemType = register("fishing_rod", maximumAmount = 1, durability = 64)
    @JvmField public val CLOCK: ItemType = register("clock")
    @JvmField public val SPYGLASS: ItemType = register("spyglass", maximumAmount = 1)
    @JvmField public val GLOWSTONE_DUST: ItemType = register("glowstone_dust")
    @JvmField public val COD: ItemType = register("cod")
    @JvmField public val SALMON: ItemType = register("salmon")
    @JvmField public val TROPICAL_FISH: ItemType = register("tropical_fish")
    @JvmField public val PUFFERFISH: ItemType = register("pufferfish")
    @JvmField public val COOKED_COD: ItemType = register("cooked_cod")
    @JvmField public val COOKED_SALMON: ItemType = register("cooked_salmon")
    @JvmField public val INK_SAC: ItemType = register("ink_sac")
    @JvmField public val GLOW_INK_SAC: ItemType = register("glow_ink_sac")
    @JvmField public val COCOA_BEANS: ItemType = register("cocoa_beans")
    @JvmField public val WHITE_DYE: ItemType = register("white_dye")
    @JvmField public val ORANGE_DYE: ItemType = register("orange_dye")
    @JvmField public val MAGENTA_DYE: ItemType = register("magenta_dye")
    @JvmField public val LIGHT_BLUE_DYE: ItemType = register("light_blue_dye")
    @JvmField public val YELLOW_DYE: ItemType = register("yellow_dye")
    @JvmField public val LIME_DYE: ItemType = register("lime_dye")
    @JvmField public val PINK_DYE: ItemType = register("pink_dye")
    @JvmField public val GRAY_DYE: ItemType = register("gray_dye")
    @JvmField public val LIGHT_GRAY_DYE: ItemType = register("light_gray_dye")
    @JvmField public val CYAN_DYE: ItemType = register("cyan_dye")
    @JvmField public val PURPLE_DYE: ItemType = register("purple_dye")
    @JvmField public val BLUE_DYE: ItemType = register("blue_dye")
    @JvmField public val BROWN_DYE: ItemType = register("brown_dye")
    @JvmField public val GREEN_DYE: ItemType = register("green_dye")
    @JvmField public val RED_DYE: ItemType = register("red_dye")
    @JvmField public val BLACK_DYE: ItemType = register("black_dye")
    @JvmField public val BONE_MEAL: ItemType = register("bone_meal")
    @JvmField public val BONE: ItemType = register("bone")
    @JvmField public val SUGAR: ItemType = register("sugar")
    @JvmField public val CAKE: ItemType = register("cake", maximumAmount = 1)
    @JvmField public val WHITE_BED: ItemType = register("white_bed", maximumAmount = 1)
    @JvmField public val ORANGE_BED: ItemType = register("orange_bed", maximumAmount = 1)
    @JvmField public val MAGENTA_BED: ItemType = register("magenta_bed", maximumAmount = 1)
    @JvmField public val LIGHT_BLUE_BED: ItemType = register("light_blue_bed", maximumAmount = 1)
    @JvmField public val YELLOW_BED: ItemType = register("yellow_bed", maximumAmount = 1)
    @JvmField public val LIME_BED: ItemType = register("lime_bed", maximumAmount = 1)
    @JvmField public val PINK_BED: ItemType = register("pink_bed", maximumAmount = 1)
    @JvmField public val GRAY_BED: ItemType = register("gray_bed", maximumAmount = 1)
    @JvmField public val LIGHT_GRAY_BED: ItemType = register("light_gray_bed", maximumAmount = 1)
    @JvmField public val CYAN_BED: ItemType = register("cyan_bed", maximumAmount = 1)
    @JvmField public val PURPLE_BED: ItemType = register("purple_bed", maximumAmount = 1)
    @JvmField public val BLUE_BED: ItemType = register("blue_bed", maximumAmount = 1)
    @JvmField public val BROWN_BED: ItemType = register("brown_bed", maximumAmount = 1)
    @JvmField public val GREEN_BED: ItemType = register("green_bed", maximumAmount = 1)
    @JvmField public val RED_BED: ItemType = register("red_bed", maximumAmount = 1)
    @JvmField public val BLACK_BED: ItemType = register("black_bed", maximumAmount = 1)
    @JvmField public val COOKIE: ItemType = register("cookie")
    @JvmField public val FILLED_MAP: ItemType = register("filled_map")
    @JvmField public val SHEARS: ItemType = register("shears", maximumAmount = 1, durability = 238)
    @JvmField public val MELON_SLICE: ItemType = register("melon_slice")
    @JvmField public val DRIED_KELP: ItemType = register("dried_kelp")
    @JvmField public val PUMPKIN_SEEDS: ItemType = register("pumpkin_seeds")
    @JvmField public val MELON_SEEDS: ItemType = register("melon_seeds")
    @JvmField public val BEEF: ItemType = register("beef")
    @JvmField public val COOKED_BEEF: ItemType = register("cooked_beef")
    @JvmField public val CHICKEN: ItemType = register("chicken")
    @JvmField public val COOKED_CHICKEN: ItemType = register("cooked_chicken")
    @JvmField public val ROTTEN_FLESH: ItemType = register("rotten_flesh")
    @JvmField public val ENDER_PEARL: ItemType = register("ender_pearl", maximumAmount = 16)
    @JvmField public val BLAZE_ROD: ItemType = register("blaze_rod")
    @JvmField public val GHAST_TEAR: ItemType = register("ghast_tear")
    @JvmField public val GOLD_NUGGET: ItemType = register("gold_nugget")
    @JvmField public val NETHER_WART: ItemType = register("nether_wart")
    @JvmField public val POTION: ItemType = register("potion", maximumAmount = 1)
    @JvmField public val GLASS_BOTTLE: ItemType = register("glass_bottle")
    @JvmField public val SPIDER_EYE: ItemType = register("spider_eye")
    @JvmField public val FERMENTED_SPIDER_EYE: ItemType = register("fermented_spider_eye")
    @JvmField public val BLAZE_POWDER: ItemType = register("blaze_powder")
    @JvmField public val MAGMA_CREAM: ItemType = register("magma_cream")
    @JvmField public val BREWING_STAND: ItemType = register("brewing_stand")
    @JvmField public val CAULDRON: ItemType = register("cauldron")
    @JvmField public val ENDER_EYE: ItemType = register("ender_eye")
    @JvmField public val GLISTERING_MELON_SLICE: ItemType = register("glistering_melon_slice")
    @JvmField public val AXOLOTL_SPAWN_EGG: ItemType = register("axolotl_spawn_egg")
    @JvmField public val BAT_SPAWN_EGG: ItemType = register("bat_spawn_egg")
    @JvmField public val BEE_SPAWN_EGG: ItemType = register("bee_spawn_egg")
    @JvmField public val BLAZE_SPAWN_EGG: ItemType = register("blaze_spawn_egg")
    @JvmField public val CAT_SPAWN_EGG: ItemType = register("cat_spawn_egg")
    @JvmField public val CAVE_SPIDER_SPAWN_EGG: ItemType = register("cave_spider_spawn_egg")
    @JvmField public val CHICKEN_SPAWN_EGG: ItemType = register("chicken_spawn_egg")
    @JvmField public val COD_SPAWN_EGG: ItemType = register("cod_spawn_egg")
    @JvmField public val COW_SPAWN_EGG: ItemType = register("cow_spawn_egg")
    @JvmField public val CREEPER_SPAWN_EGG: ItemType = register("creeper_spawn_egg")
    @JvmField public val DOLPHIN_SPAWN_EGG: ItemType = register("dolphin_spawn_egg")
    @JvmField public val DONKEY_SPAWN_EGG: ItemType = register("donkey_spawn_egg")
    @JvmField public val DROWNED_SPAWN_EGG: ItemType = register("drowned_spawn_egg")
    @JvmField public val ELDER_GUARDIAN_SPAWN_EGG: ItemType = register("elder_guardian_spawn_egg")
    @JvmField public val ENDERMAN_SPAWN_EGG: ItemType = register("enderman_spawn_egg")
    @JvmField public val ENDERMITE_SPAWN_EGG: ItemType = register("endermite_spawn_egg")
    @JvmField public val EVOKER_SPAWN_EGG: ItemType = register("evoker_spawn_egg")
    @JvmField public val FOX_SPAWN_EGG: ItemType = register("fox_spawn_egg")
    @JvmField public val GHAST_SPAWN_EGG: ItemType = register("ghast_spawn_egg")
    @JvmField public val GLOW_SQUID_SPAWN_EGG: ItemType = register("glow_squid_spawn_egg")
    @JvmField public val GOAT_SPAWN_EGG: ItemType = register("goat_spawn_egg")
    @JvmField public val GUARDIAN_SPAWN_EGG: ItemType = register("guardian_spawn_egg")
    @JvmField public val HOGLIN_SPAWN_EGG: ItemType = register("hoglin_spawn_egg")
    @JvmField public val HORSE_SPAWN_EGG: ItemType = register("horse_spawn_egg")
    @JvmField public val HUSK_SPAWN_EGG: ItemType = register("husk_spawn_egg")
    @JvmField public val LLAMA_SPAWN_EGG: ItemType = register("llama_spawn_egg")
    @JvmField public val MAGMA_CUBE_SPAWN_EGG: ItemType = register("magma_cube_spawn_egg")
    @JvmField public val MOOSHROOM_SPAWN_EGG: ItemType = register("mooshroom_spawn_egg")
    @JvmField public val MULE_SPAWN_EGG: ItemType = register("mule_spawn_egg")
    @JvmField public val OCELOT_SPAWN_EGG: ItemType = register("ocelot_spawn_egg")
    @JvmField public val PANDA_SPAWN_EGG: ItemType = register("panda_spawn_egg")
    @JvmField public val PARROT_SPAWN_EGG: ItemType = register("parrot_spawn_egg")
    @JvmField public val PHANTOM_SPAWN_EGG: ItemType = register("phantom_spawn_egg")
    @JvmField public val PIG_SPAWN_EGG: ItemType = register("pig_spawn_egg")
    @JvmField public val PIGLIN_SPAWN_EGG: ItemType = register("piglin_spawn_egg")
    @JvmField public val PIGLIN_BRUTE_SPAWN_EGG: ItemType = register("piglin_brute_spawn_egg")
    @JvmField public val PILLAGER_SPAWN_EGG: ItemType = register("pillager_spawn_egg")
    @JvmField public val POLAR_BEAR_SPAWN_EGG: ItemType = register("polar_bear_spawn_egg")
    @JvmField public val PUFFERFISH_SPAWN_EGG: ItemType = register("pufferfish_spawn_egg")
    @JvmField public val RABBIT_SPAWN_EGG: ItemType = register("rabbit_spawn_egg")
    @JvmField public val RAVAGER_SPAWN_EGG: ItemType = register("ravager_spawn_egg")
    @JvmField public val SALMON_SPAWN_EGG: ItemType = register("salmon_spawn_egg")
    @JvmField public val SHEEP_SPAWN_EGG: ItemType = register("sheep_spawn_egg")
    @JvmField public val SHULKER_SPAWN_EGG: ItemType = register("shulker_spawn_egg")
    @JvmField public val SILVERFISH_SPAWN_EGG: ItemType = register("silverfish_spawn_egg")
    @JvmField public val SKELETON_SPAWN_EGG: ItemType = register("skeleton_spawn_egg")
    @JvmField public val SKELETON_HORSE_SPAWN_EGG: ItemType = register("skeleton_horse_spawn_egg")
    @JvmField public val SLIME_SPAWN_EGG: ItemType = register("slime_spawn_egg")
    @JvmField public val SPIDER_SPAWN_EGG: ItemType = register("spider_spawn_egg")
    @JvmField public val SQUID_SPAWN_EGG: ItemType = register("squid_spawn_egg")
    @JvmField public val STRAY_SPAWN_EGG: ItemType = register("stray_spawn_egg")
    @JvmField public val STRIDER_SPAWN_EGG: ItemType = register("strider_spawn_egg")
    @JvmField public val TRADER_LLAMA_SPAWN_EGG: ItemType = register("trader_llama_spawn_egg")
    @JvmField public val TROPICAL_FISH_SPAWN_EGG: ItemType = register("tropical_fish_spawn_egg")
    @JvmField public val TURTLE_SPAWN_EGG: ItemType = register("turtle_spawn_egg")
    @JvmField public val VEX_SPAWN_EGG: ItemType = register("vex_spawn_egg")
    @JvmField public val VILLAGER_SPAWN_EGG: ItemType = register("villager_spawn_egg")
    @JvmField public val VINDICATOR_SPAWN_EGG: ItemType = register("vindicator_spawn_egg")
    @JvmField public val WANDERING_TRADER_SPAWN_EGG: ItemType = register("wandering_trader_spawn_egg")
    @JvmField public val WITCH_SPAWN_EGG: ItemType = register("witch_spawn_egg")
    @JvmField public val WITHER_SKELETON_SPAWN_EGG: ItemType = register("wither_skeleton_spawn_egg")
    @JvmField public val WOLF_SPAWN_EGG: ItemType = register("wolf_spawn_egg")
    @JvmField public val ZOGLIN_SPAWN_EGG: ItemType = register("zoglin_spawn_egg")
    @JvmField public val ZOMBIE_SPAWN_EGG: ItemType = register("zombie_spawn_egg")
    @JvmField public val ZOMBIE_HORSE_SPAWN_EGG: ItemType = register("zombie_horse_spawn_egg")
    @JvmField public val ZOMBIE_VILLAGER_SPAWN_EGG: ItemType = register("zombie_villager_spawn_egg")
    @JvmField public val ZOMBIFIED_PIGLIN_SPAWN_EGG: ItemType = register("zombified_piglin_spawn_egg")
    @JvmField public val EXPERIENCE_BOTTLE: ItemType = register("experience_bottle", ItemRarity.UNCOMMON)
    @JvmField public val FIRE_CHARGE: ItemType = register("fire_charge")
    @JvmField public val WRITABLE_BOOK: ItemType = register("writable_book", maximumAmount = 1)
    @JvmField public val WRITTEN_BOOK: ItemType = register("written_book", maximumAmount = 16)
    @JvmField public val ITEM_FRAME: ItemType = register("item_frame")
    @JvmField public val GLOW_ITEM_FRAME: ItemType = register("glow_item_frame")
    @JvmField public val FLOWER_POT: ItemType = register("flower_pot")
    @JvmField public val CARROT: ItemType = register("carrot")
    @JvmField public val POTATO: ItemType = register("potato")
    @JvmField public val BAKED_POTATO: ItemType = register("baked_potato")
    @JvmField public val POISONOUS_POTATO: ItemType = register("poisonous_potato")
    @JvmField public val MAP: ItemType = register("map")
    @JvmField public val GOLDEN_CARROT: ItemType = register("golden_carrot")
    @JvmField public val SKELETON_SKULL: ItemType = register("skeleton_skull", ItemRarity.UNCOMMON)
    @JvmField public val WITHER_SKELETON_SKULL: ItemType = register("wither_skeleton_skull", ItemRarity.UNCOMMON)
    @JvmField public val PLAYER_HEAD: ItemType = register("player_head", ItemRarity.UNCOMMON)
    @JvmField public val ZOMBIE_HEAD: ItemType = register("zombie_head", ItemRarity.UNCOMMON)
    @JvmField public val CREEPER_HEAD: ItemType = register("creeper_head", ItemRarity.UNCOMMON)
    @JvmField public val DRAGON_HEAD: ItemType = register("dragon_head", ItemRarity.UNCOMMON)
    @JvmField public val NETHER_STAR: ItemType = register("nether_star", ItemRarity.UNCOMMON)
    @JvmField public val PUMPKIN_PIE: ItemType = register("pumpkin_pie")
    @JvmField public val FIREWORK_ROCKET: ItemType = register("firework_rocket")
    @JvmField public val FIREWORK_STAR: ItemType = register("firework_star")
    @JvmField public val ENCHANTED_BOOK: ItemType =
        register("enchanted_book", ItemRarity.UNCOMMON, 1)
    @JvmField public val NETHER_BRICK: ItemType = register("nether_brick")
    @JvmField public val PRISMARINE_SHARD: ItemType = register("prismarine_shard")
    @JvmField public val PRISMARINE_CRYSTALS: ItemType = register("prismarine_crystals")
    @JvmField public val RABBIT: ItemType = register("rabbit")
    @JvmField public val COOKED_RABBIT: ItemType = register("cooked_rabbit")
    @JvmField public val RABBIT_STEW: ItemType = register("rabbit_stew", maximumAmount = 1)
    @JvmField public val RABBIT_FOOT: ItemType = register("rabbit_foot")
    @JvmField public val RABBIT_HIDE: ItemType = register("rabbit_hide")
    @JvmField public val ARMOR_STAND: ItemType = register("armor_stand", maximumAmount = 16)
    @JvmField public val IRON_HORSE_ARMOR: ItemType = register("iron_horse_armor", maximumAmount = 1)
    @JvmField public val GOLDEN_HORSE_ARMOR: ItemType = register("golden_horse_armor", maximumAmount = 1)
    @JvmField public val DIAMOND_HORSE_ARMOR: ItemType = register("diamond_horse_armor", maximumAmount = 1)
    @JvmField public val LEATHER_HORSE_ARMOR: ItemType = register("leather_horse_armor", maximumAmount = 1)
    @JvmField public val LEAD: ItemType = register("lead")
    @JvmField public val NAME_TAG: ItemType = register("name_tag")
    @JvmField public val COMMAND_BLOCK_MINECART: ItemType =
        register("command_block_minecart", ItemRarity.EPIC, 1)
    @JvmField public val MUTTON: ItemType = register("mutton")
    @JvmField public val COOKED_MUTTON: ItemType = register("cooked_mutton")
    @JvmField public val WHITE_BANNER: ItemType = register("white_banner", maximumAmount = 16)
    @JvmField public val ORANGE_BANNER: ItemType = register("orange_banner", maximumAmount = 16)
    @JvmField public val MAGENTA_BANNER: ItemType = register("magenta_banner", maximumAmount = 16)
    @JvmField public val LIGHT_BLUE_BANNER: ItemType = register("light_blue_banner", maximumAmount = 16)
    @JvmField public val YELLOW_BANNER: ItemType = register("yellow_banner", maximumAmount = 16)
    @JvmField public val LIME_BANNER: ItemType = register("lime_banner", maximumAmount = 16)
    @JvmField public val PINK_BANNER: ItemType = register("pink_banner", maximumAmount = 16)
    @JvmField public val GRAY_BANNER: ItemType = register("gray_banner", maximumAmount = 16)
    @JvmField public val LIGHT_GRAY_BANNER: ItemType = register("light_gray_banner", maximumAmount = 16)
    @JvmField public val CYAN_BANNER: ItemType = register("cyan_banner", maximumAmount = 16)
    @JvmField public val PURPLE_BANNER: ItemType = register("purple_banner", maximumAmount = 16)
    @JvmField public val BLUE_BANNER: ItemType = register("blue_banner", maximumAmount = 16)
    @JvmField public val BROWN_BANNER: ItemType = register("brown_banner", maximumAmount = 16)
    @JvmField public val GREEN_BANNER: ItemType = register("green_banner", maximumAmount = 16)
    @JvmField public val RED_BANNER: ItemType = register("red_banner", maximumAmount = 16)
    @JvmField public val BLACK_BANNER: ItemType = register("black_banner", maximumAmount = 16)
    @JvmField public val END_CRYSTAL: ItemType = register("end_crystal", ItemRarity.RARE)
    @JvmField public val CHORUS_FRUIT: ItemType = register("chorus_fruit")
    @JvmField public val POPPED_CHORUS_FRUIT: ItemType = register("popped_chorus_fruit")
    @JvmField public val BEETROOT: ItemType = register("beetroot")
    @JvmField public val BEETROOT_SEEDS: ItemType = register("beetroot_seeds")
    @JvmField public val BEETROOT_SOUP: ItemType = register("beetroot_soup", maximumAmount = 1)
    @JvmField public val DRAGON_BREATH: ItemType = register("dragon_breath", ItemRarity.UNCOMMON)
    @JvmField public val SPLASH_POTION: ItemType = register("splash_potion", maximumAmount = 1)
    @JvmField public val SPECTRAL_ARROW: ItemType = register("spectral_arrow")
    @JvmField public val TIPPED_ARROW: ItemType = register("tipped_arrow")
    @JvmField public val LINGERING_POTION: ItemType = register("lingering_potion", maximumAmount = 1)
    @JvmField public val SHIELD: ItemType = register("shield", maximumAmount = 1, durability = 336)
    @JvmField public val TOTEM_OF_UNDYING: ItemType =
        register("totem_of_undying", ItemRarity.UNCOMMON, 1)
    @JvmField public val SHULKER_SHELL: ItemType = register("shulker_shell")
    @JvmField public val IRON_NUGGET: ItemType = register("iron_nugget")
    @JvmField public val KNOWLEDGE_BOOK: ItemType = register("knowledge_book", ItemRarity.EPIC, 1)
    @JvmField public val DEBUG_STICK: ItemType = register("debug_stick", ItemRarity.EPIC, 1)
    @JvmField public val MUSIC_DISC_13: ItemType = register("music_disc_13", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_CAT: ItemType = register("music_disc_cat", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_BLOCKS: ItemType =
        register("music_disc_blocks", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_CHIRP: ItemType =
        register("music_disc_chirp", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_FAR: ItemType = register("music_disc_far", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_MALL: ItemType = register("music_disc_mall", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_MELLOHI: ItemType =
        register("music_disc_mellohi", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_STAL: ItemType = register("music_disc_stal", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_STRAD: ItemType =
        register("music_disc_strad", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_WARD: ItemType = register("music_disc_ward", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_11: ItemType = register("music_disc_11", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_WAIT: ItemType = register("music_disc_wait", ItemRarity.RARE, 1)
    @JvmField public val MUSIC_DISC_PIGSTEP: ItemType =
        register("music_disc_pigstep", ItemRarity.RARE, 1)
    @JvmField public val TRIDENT: ItemType = register("trident", maximumAmount = 1, durability = 250)
    @JvmField public val PHANTOM_MEMBRANE: ItemType = register("phantom_membrane")
    @JvmField public val NAUTILUS_SHELL: ItemType = register("nautilus_shell")
    @JvmField public val HEART_OF_THE_SEA: ItemType = register("heart_of_the_sea", ItemRarity.UNCOMMON)
    @JvmField public val CROSSBOW: ItemType = register("crossbow", maximumAmount = 1, durability = 326)
    @JvmField public val SUSPICIOUS_STEW: ItemType = register("suspicious_stew", maximumAmount = 1)
    @JvmField public val LOOM: ItemType = register("loom")
    @JvmField public val FLOWER_BANNER_PATTERN: ItemType = register("flower_banner_pattern", maximumAmount = 1)
    @JvmField public val CREEPER_BANNER_PATTERN: ItemType =
        register("creeper_banner_pattern", ItemRarity.UNCOMMON, 1)
    @JvmField public val SKULL_BANNER_PATTERN: ItemType =
        register("skull_banner_pattern", ItemRarity.UNCOMMON, 1)
    @JvmField public val MOJANG_BANNER_PATTERN: ItemType =
        register("mojang_banner_pattern", ItemRarity.EPIC, 1)
    @JvmField public val GLOBE_BANNER_PATTERN: ItemType = register("globe_banner_pattern", maximumAmount = 1)
    @JvmField public val PIGLIN_BANNER_PATTERN: ItemType = register("piglin_banner_pattern", maximumAmount = 1)
    @JvmField public val COMPOSTER: ItemType = register("composter")
    @JvmField public val BARREL: ItemType = register("barrel")
    @JvmField public val SMOKER: ItemType = register("smoker")
    @JvmField public val BLAST_FURNACE: ItemType = register("blast_furnace")
    @JvmField public val CARTOGRAPHY_TABLE: ItemType = register("cartography_table")
    @JvmField public val FLETCHING_TABLE: ItemType = register("fletching_table")
    @JvmField public val GRINDSTONE: ItemType = register("grindstone")
    @JvmField public val SMITHING_TABLE: ItemType = register("smithing_table")
    @JvmField public val STONECUTTER: ItemType = register("stonecutter")
    @JvmField public val BELL: ItemType = register("bell")
    @JvmField public val LANTERN: ItemType = register("lantern")
    @JvmField public val SOUL_LANTERN: ItemType = register("soul_lantern")
    @JvmField public val SWEET_BERRIES: ItemType = register("sweet_berries")
    @JvmField public val GLOW_BERRIES: ItemType = register("glow_berries")
    @JvmField public val CAMPFIRE: ItemType = register("campfire")
    @JvmField public val SOUL_CAMPFIRE: ItemType = register("soul_campfire")
    @JvmField public val SHROOMLIGHT: ItemType = register("shroomlight")
    @JvmField public val HONEYCOMB: ItemType = register("honeycomb")
    @JvmField public val BEE_NEST: ItemType = register("bee_nest")
    @JvmField public val BEEHIVE: ItemType = register("beehive")
    @JvmField public val HONEY_BOTTLE: ItemType = register("honey_bottle", maximumAmount = 16)
    @JvmField public val HONEYCOMB_BLOCK: ItemType = register("honeycomb_block")
    @JvmField public val LODESTONE: ItemType = register("lodestone")
    @JvmField public val CRYING_OBSIDIAN: ItemType = register("crying_obsidian")
    @JvmField public val BLACKSTONE: ItemType = register("blackstone")
    @JvmField public val BLACKSTONE_SLAB: ItemType = register("blackstone_slab")
    @JvmField public val BLACKSTONE_STAIRS: ItemType = register("blackstone_stairs")
    @JvmField public val GILDED_BLACKSTONE: ItemType = register("gilded_blackstone")
    @JvmField public val POLISHED_BLACKSTONE: ItemType = register("polished_blackstone")
    @JvmField public val POLISHED_BLACKSTONE_SLAB: ItemType = register("polished_blackstone_slab")
    @JvmField public val POLISHED_BLACKSTONE_STAIRS: ItemType = register("polished_blackstone_stairs")
    @JvmField public val CHISELED_POLISHED_BLACKSTONE: ItemType = register("chiseled_polished_blackstone")
    @JvmField public val POLISHED_BLACKSTONE_BRICKS: ItemType = register("polished_blackstone_bricks")
    @JvmField public val POLISHED_BLACKSTONE_BRICK_SLAB: ItemType = register("polished_blackstone_brick_slab")
    @JvmField public val POLISHED_BLACKSTONE_BRICK_STAIRS: ItemType = register("polished_blackstone_brick_stairs")
    @JvmField public val CRACKED_POLISHED_BLACKSTONE_BRICKS: ItemType =
        register("cracked_polished_blackstone_bricks")
    @JvmField public val RESPAWN_ANCHOR: ItemType = register("respawn_anchor")
    @JvmField public val CANDLE: ItemType = register("candle")
    @JvmField public val WHITE_CANDLE: ItemType = register("white_candle")
    @JvmField public val ORANGE_CANDLE: ItemType = register("orange_candle")
    @JvmField public val MAGENTA_CANDLE: ItemType = register("magenta_candle")
    @JvmField public val LIGHT_BLUE_CANDLE: ItemType = register("light_blue_candle")
    @JvmField public val YELLOW_CANDLE: ItemType = register("yellow_candle")
    @JvmField public val LIME_CANDLE: ItemType = register("lime_candle")
    @JvmField public val PINK_CANDLE: ItemType = register("pink_candle")
    @JvmField public val GRAY_CANDLE: ItemType = register("gray_candle")
    @JvmField public val LIGHT_GRAY_CANDLE: ItemType = register("light_gray_candle")
    @JvmField public val CYAN_CANDLE: ItemType = register("cyan_candle")
    @JvmField public val PURPLE_CANDLE: ItemType = register("purple_candle")
    @JvmField public val BLUE_CANDLE: ItemType = register("blue_candle")
    @JvmField public val BROWN_CANDLE: ItemType = register("brown_candle")
    @JvmField public val GREEN_CANDLE: ItemType = register("green_candle")
    @JvmField public val RED_CANDLE: ItemType = register("red_candle")
    @JvmField public val BLACK_CANDLE: ItemType = register("black_candle")
    @JvmField public val SMALL_AMETHYST_BUD: ItemType = register("small_amethyst_bud")
    @JvmField public val MEDIUM_AMETHYST_BUD: ItemType = register("medium_amethyst_bud")
    @JvmField public val LARGE_AMETHYST_BUD: ItemType = register("large_amethyst_bud")
    @JvmField public val AMETHYST_CLUSTER: ItemType = register("amethyst_cluster")
    @JvmField public val POINTED_DRIPSTONE: ItemType = register("pointed_dripstone")

    // @formatter:on
    @Suppress("MaxLineLength")
    private fun register(
        name: String,
        rarity: ItemRarity = ItemRarity.COMMON,
        maximumAmount: Int = 64,
        durability: Int = 0,
        isFireResistant: Boolean = false
    ): ItemType {
        val key = Key.key(name)
        return Registries.register(Registries.ITEM, key, ItemType(
            key,
            rarity,
            maximumAmount,
            durability,
            isFireResistant,
            Registries.BLOCK[key]?.translation
                ?: Component.translatable("item.${key.asString().replace(':', '.')}")
        ))
    }
}
