@SuppressWarnings("requires-transitive-automatic")
module org.kryptonmc.api {
    exports org.kryptonmc.api;
    exports org.kryptonmc.api.adventure;
    exports org.kryptonmc.api.auth;
    exports org.kryptonmc.api.block;
    exports org.kryptonmc.api.block.entity;
    exports org.kryptonmc.api.block.entity.banner;
    exports org.kryptonmc.api.block.meta;
    exports org.kryptonmc.api.block.property;
    exports org.kryptonmc.api.command;
    exports org.kryptonmc.api.command.meta;
    exports org.kryptonmc.api.effect;
    exports org.kryptonmc.api.effect.particle;
    exports org.kryptonmc.api.effect.particle.builder;
    exports org.kryptonmc.api.effect.particle.data;
    exports org.kryptonmc.api.effect.sound;
    exports org.kryptonmc.api.entity;
    exports org.kryptonmc.api.entity.ambient;
    exports org.kryptonmc.api.entity.animal;
    exports org.kryptonmc.api.entity.animal.type;
    exports org.kryptonmc.api.entity.aquatic;
    exports org.kryptonmc.api.entity.attribute;
    exports org.kryptonmc.api.entity.hanging;
    exports org.kryptonmc.api.entity.monster;
    exports org.kryptonmc.api.entity.player;
    exports org.kryptonmc.api.entity.projectile;
    exports org.kryptonmc.api.entity.vehicle;
    exports org.kryptonmc.api.event;
    exports org.kryptonmc.api.event.auth;
    exports org.kryptonmc.api.event.block;
    exports org.kryptonmc.api.event.command;
    exports org.kryptonmc.api.event.entity;
    exports org.kryptonmc.api.event.player;
    exports org.kryptonmc.api.event.server;
    exports org.kryptonmc.api.event.user.ban;
    exports org.kryptonmc.api.event.user.whitelist;
    exports org.kryptonmc.api.fluid;
    exports org.kryptonmc.api.inventory;
    exports org.kryptonmc.api.item;
    exports org.kryptonmc.api.item.data;
    exports org.kryptonmc.api.item.meta;
    exports org.kryptonmc.api.permission;
    exports org.kryptonmc.api.plugin;
    exports org.kryptonmc.api.plugin.annotation;
    exports org.kryptonmc.api.registry;
    exports org.kryptonmc.api.resource;
    exports org.kryptonmc.api.scheduling;
    exports org.kryptonmc.api.scoreboard;
    exports org.kryptonmc.api.scoreboard.criteria;
    exports org.kryptonmc.api.service;
    exports org.kryptonmc.api.statistic;
    exports org.kryptonmc.api.tags;
    exports org.kryptonmc.api.user;
    exports org.kryptonmc.api.user.ban;
    exports org.kryptonmc.api.user.whitelist;
    exports org.kryptonmc.api.util;
    exports org.kryptonmc.api.world;
    exports org.kryptonmc.api.world.biome;
    exports org.kryptonmc.api.world.damage;
    exports org.kryptonmc.api.world.damage.type;
    exports org.kryptonmc.api.world.dimension;
    exports org.kryptonmc.api.world.rule;

    requires transitive java.desktop;
    requires transitive kotlin.stdlib;
    requires transitive kotlinx.collections.immutable.jvm;
    requires transitive com.google.guice;
    requires transitive velocity.brigadier;
    requires transitive net.kyori.adventure;
    requires transitive net.kyori.adventure.key;
    requires transitive org.spongepowered.math;
    requires transitive spark.api;
    requires static org.jetbrains.annotations;
}
