name: "Codecov test & upload"

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Setup JDK 16"
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: "Grant execute permission for gradlew"
        run: chmod +x gradlew
      - name: "Build with Gradle"
        run: ./gradlew clean build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Run tests"
        run: ./gradlew clean test
      - name: "Coverage Report"
        run: ./gradlew jacocoTestReport
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          files: server/build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: false
