name: "Pull Request Validation Build"

on:
  pull_request: null

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v2"
      - name: "setup jdk 11"
        uses: "actions/setup-java@v1"
        with:
          java-version: "16"
      - name: "build"
        run: "./gradlew clean test :krypton-bootstrap:shadowJar"
